'use strict';var aa=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},ca=ba(this),g=function(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=
0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&aa(c,a,{configurable:!0,writable:!0,value:b})}},da=function(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(k){k.done?d(k.value):Promise.resolve(k.value).then(b,c).then(f,e)}f(a.next())})},h=function(a){return da(a())};
g("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&c.push(b[d]);return c}});g("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&c.push([d,b[d]]);return c}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var l=this||self;var ia=function(a){switch(a){case m.name:return m;case n.name:return n;case p.name:return p;case ea.name:return ea;case fa.name:return fa;default:let b=ha.get(a);b||(b=new q(a),ha.set(a,b));return b}},q=class{constructor(a){this.name=a}toString(){return this.name}},ha=new Map,m=new q("async"),n=new q("generic"),p=new q("runtime"),ea=new q("system"),fa=new q("crypto"),r=class extends Error{constructor(a,b,c){super(c);this.code=a;this.category=b;Object.setPrototypeOf(this,new.target.prototype)}toString(){return`${this.category}:${this.code} (${this.message||
"Undefined error."})`}};var ja=class{constructor(){var a=void 0,b=void 0;this.promise=new Promise((c,d)=>{a=c;b=d});this.resolve=a;this.reject=b}},t=class extends r{constructor(a,b="One or more errors occurred."){super(1,m,b);this.errors=a;Object.setPrototypeOf(this,new.target.prototype)}flatten(){for(var a=[],b=[this.errors.slice(0)];b.length!==0;){let c=b[0];for(;c.length!==0;){let d=c.shift();if(d instanceof t){b.unshift(d.errors.slice(0));break}else a.push(d)}b[0]===c&&b.shift()}return new t(a,this.message)}};var ka=class{constructor(){this.i=[]}subscribe(a){this.i.push(a)}unsubscribe(a){a=this.i.indexOf(a);if(a===-1)return!1;this.i.splice(a,1);return!0}publish(...a){var b=[],c=this.i.slice(0);for(let d of c)b.push(d(...a));return b}};function la(a,b,...c){return h(function*(){var d=new ja,e={magic:91556947316803,host:a!==null&&typeof a==="number"?"*":a,method:b,args:c},f=k=>{var v=chrome.runtime.lastError;v?d.reject(new r(1,p,`Operation '${String(b)}' failed. ${v.message||"Undefined error."}`)):k.error!==void 0?d.reject(ma(k.error)):d.resolve(k.result)};a!==null&&typeof a==="number"?chrome.tabs.sendMessage(a,e,f):chrome.runtime.sendMessage(e,f);return d.promise})}
function ma(a){switch(a.type){case 0:return a.object;case 1:return Error(a.message);case 2:return new r(a.code,ia(a.category),a.message);case 3:return new t(a.errors.map(ma),a.message)}};var na=function(a,b){for(let [d,e]of a.R){let f=d;var c=e;if(b.every(k=>f.has(k)))return c}c={};for(let d of b)Object.defineProperty(c,d,{value:(...e)=>a.invoke(d,...e),writable:!1});a.R.set(new Set(b),c);return c},oa=class{constructor(a="*"){this.host=a;this.events=new Map;this.R=new Map}invoke(a,...b){var c=this;return h(function*(){return la(c.host,a,...b)})}};var u=class{constructor(a,b){this.name=a;this.value=b}toString(){return this.name}},w=new u("OFF",Infinity),pa=new u("SEVERE",1E3),qa=new u("WARNING",900),ra=new u("INFO",800),sa=new u("CONFIG",700),ta=[w,new u("SHOUT",1200),pa,qa,ra,sa,new u("FINE",500),new u("FINER",400),new u("FINEST",300),new u("ALL",0)],ua=class{constructor(){this.o=0;this.clear()}clear(){this.F=Array(this.o);this.G=-1;this.J=!1}},x,va=class{constructor(a,b,c){this.reset(a||w,b,c,void 0,void 0)}reset(a,b,c,d){d||Date.now();this.aa=
b}getMessage(){return this.aa}},wa=function(a){return a.level?a.level:a.parent?wa(a.parent):w},xa=class{constructor(a,b=null){this.level=null;this.i=[];this.parent=b||null;this.children=[];this.Z={getName:()=>a}}publish(a){for(var b=this;b;)b.i.forEach(c=>{c(a)}),b=b.parent}},y=function(a,b){var c=a.entries[b];if(c)return c;c=b.lastIndexOf(".");c=b.slice(0,Math.max(c,0));c=y(a,c);var d=new xa(b,c);a.entries[b]=d;c.children.push(d);return d},ya=class{constructor(){this.entries={};var a=new xa("");
a.level=sa;this.entries[""]=a}},z,A=function(){z||(z=new ya);return z},B=function(a,b,c){var d;if(d=a)if(d=a&&b){d=b.value;var e=a?wa(y(A(),a.getName())):w;d=d>=e.value}if(d){b=b||w;d=y(A(),a.getName());typeof c==="function"&&(c=c());x||(x=new ua);e=x;a=a.getName();if(e.o>0){var f=(e.G+1)%e.o;e.G=f;e.J?(e=e.F[f],e.reset(b,c,a),a=e):(e.J=f==e.o-1,a=e.F[f]=new va(b,c,a))}else a=new va(b,c,a);d.publish(a)}};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
function C(a){return a.toString().indexOf("`")===-1}C(a=>a``)||C(a=>a`\0`)||C(a=>a`\n`)||C(a=>a`\u0000`);"ARTICLE SECTION NAV ASIDE H1 H2 H3 H4 H5 H6 HEADER FOOTER ADDRESS P HR PRE BLOCKQUOTE OL UL LH LI DL DT DD FIGURE FIGCAPTION MAIN DIV EM STRONG SMALL S CITE Q DFN ABBR RUBY RB RT RTC RP DATA TIME CODE VAR SAMP KBD SUB SUP I B U MARK BDI BDO SPAN BR WBR NOBR INS DEL PICTURE PARAM TRACK MAP TABLE CAPTION COLGROUP COL TBODY THEAD TFOOT TR TD TH SELECT DATALIST OPTGROUP OPTION OUTPUT PROGRESS METER FIELDSET LEGEND DETAILS SUMMARY MENU DIALOG SLOT CANVAS FONT CENTER ACRONYM BASEFONT BIG DIR HGROUP STRIKE TT".split(" ").concat(["BUTTON",
"INPUT"]);var Aa=class{constructor(){this.name="ProfileUserProvider";this.target=y(A(),"ProfileUserProvider").Z}log(a,b){B(this.target,a!=null?a:D,b)}error(a){B(this.target,pa,a)}warn(a){B(this.target,qa,a)}info(a){B(this.target,ra,a)}debug(a){B(this.target,D,a)}trace(a){B(this.target,za,a)}};y(A(),"");var D=new u("DEBUG",600),za=new u("TRACE",100);ta.push(D);ta.push(za);const E=new Aa;function Fa(a){return h(function*(){return new Promise((b,c)=>{var d=e=>{var f=chrome.runtime.lastError;f?c(new r(1,p,f.message||"Call to c.i.getProfileUserInfo failed.")):b(e)};a?chrome.identity.getProfileUserInfo({accountStatus:chrome.identity.AccountStatus.ANY},d):chrome.identity.getProfileUserInfo(d)})})}
var Ha=function(a,b,c){h(function*(){E.info(`Account ${b.id} has signed ${c?"in":"out"}.`);yield Ga(a);a.ea.publish(c)})},Ga=function(a){return h(function*(){try{let c=yield Fa(a.O);var b=c.id||void 0;a.H=c.email||void 0}catch(c){E.warn(`Failed to get Profile User info. ${c.message}`)}a.v!==b&&(a.v=b,a.X.publish(a.id),E.info(`Profile Account ID: ${a.id}.`))})},Ia=class{constructor(a){this.ca=a;this.X=new ka;this.ea=new ka;this.I=!1;this.da=(b,c)=>{Ha(this,b,c)}}get id(){return this.v}get email(){return this.H}initialize(){var a=
this;return h(function*(){if(a.I)throw new r(416,n,"ProfileUserProvider has already been initialized.");E.trace("Initializing...");try{let b=yield Fa(a.O);a.v=b.id||void 0;a.H=b.email||void 0}catch(b){E.warn(`Failed to get Profile User info. ${b.message}`)}E.trace(`Profile Account ${a.email}, ID '${a.id}'.`);chrome.identity.onSignInChanged.addListener(a.da);a.I=!0;E.trace("Done.");return a.id})}get O(){this.K===void 0&&(this.K=this.ca.V.Y(84));return this.K}};let Ja=void 0;var F,G;a:{for(var Ka=["CLOSURE_FLAGS"],H=l,I=0;I<Ka.length;I++)if(H=H[Ka[I]],H==null){G=null;break a}G=H}var La=G&&G[610401301];F=La!=null?La:!1;const Ma=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function Na(a,b){var c=0;a=Ma(String(a)).split(".");b=Ma(String(b)).split(".");var d=Math.max(a.length,b.length);for(let k=0;c==0&&k<d;k++){var e=a[k]||"",f=b[k]||"";do{e=/(\d*)(\D*)(.*)/.exec(e)||["","","",""];f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];if(e[0].length==0&&f[0].length==0)break;c=J(e[1].length==0?0:parseInt(e[1],10),f[1].length==0?0:parseInt(f[1],10))||J(e[2].length==0,f[2].length==0)||J(e[2],f[2]);e=e[3];f=f[3]}while(c==0)}return c}function J(a,b){return a<b?-1:a>b?1:0};function Oa(){var a=l.navigator;return a&&(a=a.userAgent)?a:""}var K;const Pa=l.navigator;K=Pa?Pa.userAgentData||null:null;function L(a){if(!F||!K)return!1;for(let b=0;b<K.brands.length;b++){let {brand:c}=K.brands[b];if(c&&c.indexOf(a)!=-1)return!0}return!1}function M(a){return Oa().indexOf(a)!=-1};var N=class{constructor(a){this.ga=a}};var O=new class{constructor(a){this.N=a;this.A=this.B=void 0;this.P=!1}u(){if(K)return this.B}load(){var a=this;return h(function*(){if(K)return a.A||(a.P=!0,a.A=(()=>h(function*(){try{let b=yield K.getHighEntropyValues([a.N]);a.B=b[a.N];return a.B}finally{a.P=!1}}))()),yield a.A})}}("fullVersionList");function P(a=!1){return a||F?!!K&&K.brands.length>0:!1}function Q(){return P()?!1:M("Opera")}function R(){return P()?L("Microsoft Edge"):M("Edg/")}function S(){return P()?L("Opera"):M("OPR")}function T(){return M("Firefox")||M("FxiOS")}function U(){return P()?L("Chromium"):(M("Chrome")||M("CriOS"))&&!(P()?0:M("Edge"))||M("Silk")}function Qa(a){var b={};a.forEach(c=>{b[c[0]]=c[1]});return c=>b[c.find(d=>d in b)]||""}
function V(a){var b=Oa();if(a==="Internet Explorer"){if(P()?0:M("Trident")||M("MSIE"))if((a=/rv: *([\d\.]*)/.exec(b))&&a[1])b=a[1];else{a="";var c=/MSIE +([\d\.]+)/.exec(b);if(c&&c[1])if(b=/Trident\/(\d.\d)/.exec(b),c[1]=="7.0")if(b&&b[1])switch(b[1]){case "4.0":a="8.0";break;case "5.0":a="9.0";break;case "6.0":a="10.0";break;case "7.0":a="11.0"}else a="7.0";else a=c[1];b=a}else b="";return b}var d=RegExp("([A-Z][\\w ]+)/([^\\s]+)\\s*(?:\\((.*?)\\))?","g");c=[];for(var e;e=d.exec(b);)c.push([e[1],
e[2],e[3]||void 0]);b=Qa(c);switch(a){case "Opera":if(Q())return b(["Version","Opera"]);if(S())return b(["OPR"]);break;case "Microsoft Edge":if(P()?0:M("Edge"))return b(["Edge"]);if(R())return b(["Edg"]);break;case "Chromium":if(U())return b(["Chrome","CriOS","HeadlessChrome"])}return a==="Firefox"&&T()||a==="Safari"&&M("Safari")&&!(U()||(P()?0:M("Coast"))||Q()||(P()?0:M("Edge"))||R()||S()||T()||M("Silk")||M("Android"))||a==="Android Browser"&&M("Android")&&!(U()||T()||Q()||M("Silk"))||a==="Silk"&&
M("Silk")?(b=c[2])&&b[1]||"":""}function Ra(){if(P()){var a=K.brands.find(({brand:b})=>b==="Chromium");if(!a||!a.version)return NaN;a=a.version.split(".")}else{a=V("Chromium");if(a==="")return NaN;a=a.split(".")}return a.length===0?NaN:Number(a[0])}
class Sa{constructor(a,b,c){this.C=a;this.U=new N(c);this.T=b}u(){if(this.T){var a=O.u();if(a!==void 0)return a=a.find(({brand:b})=>this.C===b),new N(a.version)}if(W)return this.U}load(){var a=this;return h(function*(){if(a.T){var b=yield O.load();if(b!==void 0)return b=b.find(({brand:c})=>a.C===c),new N(b.version)}else yield 0;W=!0;return a.U})}}let W=!1;function Ta(){return h(function*(){P(!0)&&(yield O.load());W=!0})}
function Ua(a){var b="";Ra()>=98||(b=V(a));var c=a!=="Silk"&&P(!0);if(c){if(!K.brands.find(({brand:d})=>d===a))return}else if(b==="")return;return new Sa(a,c,b)}function Va(a){if(P(!0)){var b=Ua(a);return b?(b=b.u())?b.ga:K.brands.find(({brand:c})=>c===a).version:""}return V(a)};function Wa(){return h(function*(){return new Promise((a,b)=>{chrome.runtime.getPlatformInfo(c=>{var d=chrome.runtime.lastError;d&&b(new r(1,p,d.message||"Call to c.r.getPlatformInfo failed."));a(c)})})})}function Xa(a){switch(a){case "mac":return 1;case "win":return 2;case "cros":return 4;case "linux":return 3;default:return 0}}function Ya(){switch(U()?R()?2:S()?4:1:T()?3:0){case 2:return"Microsoft Edge";case 1:return"Chromium";case 3:return"Firefox";case 4:return"Opera"}}
function Za(){return h(function*(){var a=Ya();return a?(yield Ta(),Va(a)):""})}function $a(){return h(function*(){var a=yield Wa();a=Xa(a.os);var b=yield Za();return{na:a,V:{browser:U()?R()?2:S()?4:1:T()?3:0,version:b,Y:c=>Na(b,c)>=0,la:c=>Na(b,c)<=0},oa:{version:chrome.runtime.getManifest().version,ma:chrome.runtime.getManifest().manifest_version}}})};var ab=function(a,b){return new Promise((c,d)=>{a.j.set(b,()=>{var e=chrome.runtime.lastError;e?d(new r(5,p,e.message||"Call to c.s.l.set failed.")):c()})})},bb=function(a,b){return new Promise((c,d)=>{a.j.get(b,e=>{var f=chrome.runtime.lastError;f?d(new r(5,p,f.message||"Call to c.s.l.get failed.")):c(e)})})};
class cb{constructor(a){this.j=a}set(a,b){var c=this;return h(function*(){return ab(c,{[a]:b})})}get(a,b){var c=this;return h(function*(){var d;return(d=(yield bb(c,[a]))[a])!=null?d:b})}getAll(){return new Promise((a,b)=>{this.j.get(null,c=>{var d=chrome.runtime.lastError;d?b(new r(5,p,d.message||"Call to c.s.l.getAll failed.")):a(c)})})}remove(a){return new Promise((b,c)=>{this.j.remove(a,()=>{var d=chrome.runtime.lastError;d?c(new r(5,p,d.message||"Call to c.s.l.remove failed.")):b()})})}removeAll(a){return new Promise((b,
c)=>{this.j.remove(a,()=>{var d=chrome.runtime.lastError;d?c(new r(5,p,d.message||"Call to c.s.l.remove failed.")):b()})})}}let X,Z;var db={get local(){X||(X=new cb(chrome.storage.local));return X},get managed(){Z||(Z=new cb(chrome.storage.managed));return Z}};var eb=function(a){return h(function*(){var b=yield a.ba,c=document.getElementById("user-email");if(c){let d;c.textContent=(d=b.email)!=null?d:"N/A"}})},fb=function(){return h(function*(){var a=document.getElementById("proxy-mode"),b=document.getElementById("proxy-label"),c=document.getElementById("proxy-rules");chrome.proxyOverrideRulesPrivate&&chrome.proxyOverrideRulesPrivate.rules?(a&&(a.textContent="Proxy Override Rules (POR)"),chrome.proxyOverrideRulesPrivate.rules.get({},d=>{b&&(b.textContent=
"Proxy Override Rules:");c&&(c.textContent=JSON.stringify(d.value,null,2))})):chrome.proxy&&chrome.proxy.settings?chrome.proxy.settings.get({},d=>{b&&(b.textContent="PAC Script:");if(c){let e,f;c.textContent=((e=d.value.pacScript)==null?void 0:e.url)||((f=d.value.pacScript)==null?void 0:f.data)||"N/A"}}):(a&&(a.textContent="N/A (API not available)"),b&&(b.textContent="N/A"),c&&(c.textContent="N/A"))})},ib=function(a){return h(function*(){var b=document.getElementById("quirks-container");if(b)try{var c=
yield a.background.getQuirks();b.textContent="";let e=document.createElement("table");e.className="mdl-data-table mdl-js-data-table";var d=document.createElement("thead");let f=document.createElement("tr"),k=document.createElement("th");k.textContent="Name";let v=document.createElement("th");v.textContent="Value";f.appendChild(k);f.appendChild(v);d.appendChild(f);e.appendChild(d);let Ba=document.createElement("tbody");for(let [gb,hb]of Object.entries(c)){c=gb;d=hb;let Y=document.createElement("tr"),
Ca=document.createElement("td");Ca.textContent=c;let Da=document.createElement("td"),Ea;Da.textContent=String((Ea=d.value)!=null?Ea:d.default);Y.appendChild(Ca);Y.appendChild(Da);Ba.appendChild(Y)}e.appendChild(Ba);b.appendChild(e)}catch(e){b.textContent="Failed to load quirks: "+String(e)}})},jb=function(a){return h(function*(){var b=document.getElementById("policy-config");if(b)try{let c=yield a.fa.getAll();b.textContent=JSON.stringify(c,null,2)}catch(c){b.textContent="Failed to load policy: "+
String(c)}})},kb=function(a){var b=document.getElementById("refresh-routes");b&&(b.onclick=()=>h(function*(){b.setAttribute("disabled","true");var e=b.textContent;b.textContent="Refreshing...";try{yield a.S["routes:refresh"]({}),alert("Routes refreshed successfully!"),yield fb()}catch(f){alert("Failed to refresh routes: "+String(f))}finally{b.removeAttribute("disabled"),b.textContent=e}}));var c=document.getElementById("reload-extension");c&&(c.onclick=()=>{chrome.runtime.reload()});var d=document.getElementById("clear-auth-cache");
d&&(d.onclick=()=>h(function*(){d.setAttribute("disabled","true");var e=d.textContent;d.textContent="Clearing...";try{yield a.S["authCache:clear"](),alert("Auth cache cleared successfully!")}catch(f){alert("Failed to clear auth cache: "+String(f))}finally{d.removeAttribute("disabled"),d.textContent=e}}))},ob=class{constructor(){var a=lb,b=mb,c=nb(),d=db.managed;this.background=a;this.S=b;this.ba=c;this.fa=d}initialize(){var a=this;return h(function*(){yield eb(a);yield fb();yield ib(a);yield jb(a);
kb(a)})}};const lb=na(new oa,Object.values({ha:"hello",ia:"getQuirks",ja:"updateQuirks",ka:"uiEvent"})),mb=na(new oa("securityGateway/external"),["routes:refresh","authCache:clear"]);function nb(){return h(function*(){var a=yield $a();if(Ja)throw new r(416,n,"Runtime Info has already been initialized.");Ja=a;a=new Ia(a);yield a.initialize();return a})}chrome.runtime&&chrome.runtime.id&&document.addEventListener("DOMContentLoaded",()=>h(function*(){yield(new ob).initialize()}));
