'use strict';var h,aa=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},ca=ba(this),l=function(a,b){if(b)a:{var c=ca;a=a.split(".");
for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&aa(c,a,{configurable:!0,writable:!0,value:b})}},da=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},m=function(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})};
l("Symbol.asyncIterator",function(a){return a?a:Symbol("Symbol.asyncIterator")});
var fa=function(a){var b=a[Symbol.asyncIterator];if(b!==void 0)a=b.call(a);else{b=ea;var c=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(c)a=c.call(a);else if(typeof a.length=="number")a={next:da(a)};else throw Error(String(a)+" is not an iterable or ArrayLike");a=new b(a)}return a},ea=function(a){function b(c){return Promise.resolve(c.value).then(function(d){return{value:d,done:!!c.done}})}this[Symbol.asyncIterator]=function(){return this};this[Symbol.iterator]=function(){return a};
this.next=function(c){return(new Promise(function(d){d(a.next(c))})).then(b)};this["throw"]=function(c){return(new Promise(function(d,e){var f=a["throw"];f!==void 0?d(f.call(a,c)):(d=a["return"],d!==void 0&&d.call(a),e(new TypeError("no `throw` method")))})).then(b)};a["return"]!==void 0&&(this["return"]=function(c){return(new Promise(function(d){d(a["return"](c))})).then(b)})},n=function(a,b){this.action=a;this.value=b},ha=function(a,b,c,d){this.method=a;this.u=b;this.resolve=c;this.reject=d},ia=
function(a){this.frame=a;this.next=null},r=function(){this.P=this.v=null};r.prototype.isEmpty=function(){return this.v===null};r.prototype.first=function(){if(this.v)return this.v.frame;throw Error("no frames in executionQueue");};r.prototype.drop=function(){this.v&&(this.v=this.v.next,this.v||(this.P=null))};r.prototype.enqueue=function(a){a=new ia(a);this.P?this.P.next=a:this.v=a;this.P=a};
var u=function(a){this.ia=a;this.j=null;this.i=new r;this[Symbol.asyncIterator]=function(){return this};var b=this;this.xa=function(c){var d=b.i.first();c.done===!0?(b.j=null,d.method!=="return"&&(d.method="next",d.u=c.value)):(d.resolve({value:c.value,done:!1}),b.i.drop());t(b)};this.wa=function(c){ja(b,c)};this.I=function(c){ka(b,c)}},la=function(a,b,c){return new Promise(function(d,e){var f=a.i.isEmpty();a.i.enqueue(new ha(b,c,d,e));f&&t(a)})};
u.prototype.next=function(a){return la(this,"next",a)};u.prototype.return=function(a){return la(this,"return",new n(0,a))};u.prototype.throw=function(a){return la(this,"throw",a)};
var t=function(a){if(!a.i.isEmpty())try{a.j?ma(a):na(a)}catch(b){ka(a,b)}},na=function(a){var b=a.i.first();try{var c=a.ia[b.method](b.u);if(c.value instanceof n)switch(c.value.action){case 0:Promise.resolve(c.value.value).then(function(d){b.resolve({value:d,done:c.done});a.i.drop();t(a)},function(d){b.reject(d);a.i.drop();t(a)}).catch(a.I);break;case 1:a.j=fa(c.value.value);b.method="next";b.u=void 0;t(a);break;case 2:Promise.resolve(c.value.value).then(function(d){b.method="next";b.u=d;t(a)},function(d){b.method=
"throw";b.u=d;t(a)}).catch(a.I);break;default:throw Error("Unrecognized AsyncGeneratorWrapper$ActionEnum");}else b.resolve(c),a.i.drop(),t(a)}catch(d){b.reject(d),a.i.drop(),t(a)}},ma=function(a){if(!a.j)throw Error("no delegate to perform execution");var b=a.i.first();if(b.method in a.j)try{var c=b.u;c instanceof n&&(c=c.value);a.j[b.method](c).then(a.xa,a.wa).catch(a.I)}catch(d){ja(a,d)}else if(b.method==="throw")if(c=a.j,a.j=null,"return"in c)try{Promise.resolve(c["return"]()).then(function(){b.u=
new TypeError("The iterator does not provide a 'throw' method");t(a)},function(d){b.u=d;t(a)}).catch(a.I)}catch(d){b.u=d,t(a)}else b.u=new TypeError("The iterator does not provide a 'throw' method"),t(a);else a.j=null,t(a)},ja=function(a,b){var c=a.i.first();a.j=null;c.method="throw";c.u=b;t(a)},ka=function(a,b){a.i.isEmpty()||(a.i.first().reject(b),a.i.drop());a.j&&"return"in a.j&&(a.j["return"](void 0),a.j=null);a.ia["return"](void 0);t(a)};l("globalThis",function(a){return a||ca});
l("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});l("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&c.push([d,b[d]]);return c}});
l("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&c.push(b[d]);return c}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var v=this||self,pa=function(a){a=a.split(".");for(var b=v,c=0;c<a.length;c++)if(b=b[a[c]],b==null)return null;return b},qa=function(a){var b=typeof a;b=b!="object"?b:a?Array.isArray(a)?"array":b:"null";return b=="array"||b=="object"&&typeof a.length=="number"},ra=function(a){var b=typeof a;return b=="object"&&a!=null||b=="function"},sa=function(a,b,c){return a.call.apply(a.bind,arguments)},ta=function(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);
return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},ua=function(a,b,c){ua=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?sa:ta;return ua.apply(null,arguments)},va=function(a,b){function c(){}c.prototype=b.prototype;a.Ma=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ja=function(d,e,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-
2]=arguments[k];return b.prototype[e].apply(d,g)}};var wa={Fa:"hello",Ga:"getQuirks",Ha:"updateQuirks",Ia:"uiEvent"};var Da=function(a){switch(a){case xa.name:return xa;case ya.name:return ya;case za.name:return za;case Aa.name:return Aa;case Ba.name:return Ba;default:let b=Ca.get(a);b||(b=new w(a),Ca.set(a,b));return b}},w=class{constructor(a){this.name=a}toString(){return this.name}},Ca=new Map,xa=new w("async"),ya=new w("generic"),za=new w("runtime"),Aa=new w("system"),Ba=new w("crypto"),x=class extends Error{constructor(a,b,c){super(c);this.code=a;this.category=b;Object.setPrototypeOf(this,new.target.prototype)}toString(){return`${this.category}:${this.code} (${this.message||
"Undefined error."})`}};function y(a){throw new x(416,ya,a);};/*

 ISC License (ISC)
 Copyright (c) 2016, Jake Archibald <jaffathecake\@gmail.com>

 Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee
 is hereby granted, provided that the above copyright notice and this permission notice appear in all
 copies.

 THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS
 SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
 AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
 OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
 SOFTWARE.
*/
var Fa=a=>(Ea||(Ea=[IDBDatabase,IDBObjectStore,IDBIndex,IDBCursor,IDBTransaction])).some(b=>a instanceof b);let Ea,Ga;const Ha=new WeakMap,Ia=new WeakMap,Ja=new WeakMap,Ka=new WeakMap;var z=new WeakMap;function La(a){var b=new Promise((c,d)=>{var e=()=>{a.removeEventListener("success",f);a.removeEventListener("error",g)},f=()=>{c(A(a.result));e()},g=()=>{d(a.error);e()};a.addEventListener("success",f);a.addEventListener("error",g)});b.then(c=>{c instanceof IDBCursor&&Ha.set(c,a)}).catch(()=>{});z.set(b,a);return b}
function Ma(a){if(!Ia.has(a)){var b=new Promise((c,d)=>{var e=()=>{a.removeEventListener("complete",f);a.removeEventListener("error",g);a.removeEventListener("abort",g)},f=()=>{c();e()},g=()=>{d(a.error||new DOMException("AbortError","AbortError"));e()};a.addEventListener("complete",f);a.addEventListener("error",g);a.addEventListener("abort",g)});Ia.set(a,b)}}
let Na={get(a,b,c){if(a instanceof IDBTransaction){if(b==="done")return Ia.get(a);if(b==="objectStoreNames")return a.objectStoreNames||Ja.get(a);if(b==="store")return c.objectStoreNames[1]?void 0:c.objectStore(c.objectStoreNames[0])}return A(a[b])},set(a,b,c){a[b]=c;return!0},has(a,b){return a instanceof IDBTransaction&&(b==="done"||b==="store")?!0:b in a}};
function Oa(a){return a!==IDBDatabase.prototype.transaction||"objectStoreNames"in IDBTransaction.prototype?(Ga||(Ga=[IDBCursor.prototype.advance,IDBCursor.prototype.continue,IDBCursor.prototype.continuePrimaryKey])).includes(a)?function(...b){a.apply(z.get(this),b);return A(Ha.get(this))}:function(...b){return A(a.apply(z.get(this),b))}:function(b,...c){c=a.call(z.get(this),b,...c);Ja.set(c,b.sort?b.sort():[b]);return A(c)}}
function A(a){if(a instanceof IDBRequest)return La(a);if(Ka.has(a))return Ka.get(a);if(typeof a==="function")var b=Oa(a);else a instanceof IDBTransaction&&Ma(a),b=Fa(a)?new Proxy(a,Na):a;b!==a&&(Ka.set(a,b),z.set(b,a));return b};const Pa=["get","getKey","getAll","getAllKeys","count"],Qa=["put","add","delete","clear"],Ra=new Map;
function Sa(a,b){if(a instanceof IDBDatabase&&!(b in a)&&typeof b==="string"){if(Ra.get(b))return Ra.get(b);var c=b.replace(/FromIndex$/,""),d=b!==c,e=Qa.includes(c);if(c in(d?IDBIndex:IDBObjectStore).prototype&&(e||Pa.includes(c)))return a=function(f,...g){var k=this;return m(function*(){var p=k.transaction(f,e?"readwrite":"readonly"),q=p.store;d&&(q=q.index(g.shift()));return(yield Promise.all([q[c](...g),e&&p.done]))[0]}())},Ra.set(b,a),a}}
Na=(a=>Object.assign({},a,{get:(b,c,d)=>Sa(b,c)||a.get(b,c,d),has:(b,c)=>!!Sa(b,c)||a.has(b,c)}))(Na);function Ta({blocked:a,upgrade:b,Ka:c,Na:d}={}){var e=indexedDB.open("log-db",1),f=A(e);b&&e.addEventListener("upgradeneeded",g=>{b(A(e.result),g.oldVersion,g.newVersion,A(e.transaction))});a&&e.addEventListener("blocked",()=>a());f.then(g=>{d&&g.addEventListener("close",()=>d());c&&g.addEventListener("versionchange",()=>c())}).catch(()=>{});return f};var Va=function(a,b,c){m(function*(){c.ct=a.context;c.ep=Ua;yield b.add(c)}())},Wa=function(a,b,c){return m(function*(){a.db||y("Log database is not initialized.");var d=a.db.transaction("logs","readonly"),e=d.objectStore("logs");e=b==="id"||c===void 0?yield e.getAll(c):yield e.index(b).getAll(c);yield d.done;return e}())},Xa=class{constructor(){this.context="log_script";this.capacity=1E3;this.Ea=void 0;this.db=null}initialize(){var a=this;return m(function*(){a.db&&y("Log database is already initialized.");
var b=Object.assign({},a.Ea);b.upgrade===void 0&&(b.upgrade=c=>{a.createObjectStore(c)});a.db=yield Ta(b);a.trim()}())}createObjectStore(a){a.objectStoreNames.contains("logs")||(a=a.createObjectStore("logs",{keyPath:"id",autoIncrement:!0}),a.createIndex("ts","ts",{unique:!1}),a.createIndex("lvl","lvl",{unique:!1}),a.createIndex("cmp","cmp",{unique:!1}),a.createIndex("ep","ep",{unique:!1}),a.createIndex("ct","ct",{unique:!1}))}trim(){var a=this;return m(function*(){var b=a.db.transaction("logs","readwrite"),
c=b.objectStore("logs");if(!(a.capacity>=(yield c.count()))){var d=yield c.openKeyCursor(null,"prev");if(d!==null)return yield c.delete(IDBKeyRange.upperBound(d.primaryKey-a.capacity,!1)),b.done}}())}write(a){var b=this;return m(function*(){b.db||y("Log database is not initialized.");if(!Array.isArray(a)||a.length!==0){var c=b.db.transaction("logs","readwrite"),d=c.objectStore("logs");Array.isArray(a)?a.forEach(e=>{Va(b,d,e)}):Va(b,d,a);c.commit();return c.done}}())}range(a,b,c="next"){var d=this;
return function(){return new u(function*(){d.db||y("Log database is not initialized.");var e=d.db.transaction("logs","readonly"),f=e.objectStore("logs");a==="id"?f=yield new n(2,f.openCursor(b,c)):(f=f.index(a),f=yield new n(2,f.openCursor(b,c)));for(;f;)yield new n(0,f.value),f=yield new n(2,f.continue());return new n(0,e.done)}())}()}},Ua=Date.now(),Ya=class{constructor(a){this.range=a}get K(){return this.range}};const Za=["id","ts","ep"];
function ab(a,b,c){Za.includes(a)&&b.sort((d,e)=>d.id-e.id);return c===void 0||c.count>=b.length?b:c.temporalDescending?b.slice(-c.count):b.slice(0,c.count)}
var bb=function(a,b,c,d,e){return m(function*(){var f=void 0,g=void 0;Za.includes(b)&&(f=(e==null?0:e.temporalDescending)?"prev":"next",g=e==null?void 0:e.count);var k=a.fa.range(b,c,f),p=[],q;try{for(var oa=fa(k);;){var F=void 0;F=yield oa.next();if(F.done)break;let U=F.value;if([...d.entries()].every(([dc,ec])=>ec.includes(U[dc]))&&(p.push(U),g!==void 0&&p.length>=g))break}}catch(U){var $a={error:U}}finally{try{F&&!F.done&&(q=oa.return)&&(yield q.call(oa))}finally{if($a)throw $a.error;}}f==="prev"&&
p.reverse();return ab(b,p,e)}())},db=class{constructor(){this.fa=cb}query(a){var b=this;return m(function*(){var c=new Map;a.id!==void 0&&c.set("id",a.id.K);a.timestamp!==void 0&&c.set("ts",a.timestamp.K);a.epoch!==void 0&&c.set("ep",a.epoch.K);a.logLevel!==void 0&&c.set("lvl",a.logLevel.K);a.context&&c.set("ct",IDBKeyRange.only(a.context));if(a.componentsPrefix!==void 0&&a.componentsPrefix.length>0){var d=c.set;var e=a.componentsPrefix;let f=[...e];f[f.length-1]+=String.fromCharCode(65535);e=IDBKeyRange.bound(e,
f,!1,!1);d.call(c,"cmp",e)}d=c.size>0&&!c.has("id")?c.keys().next().value:"id";e=c.get(d);if(c.size<=1)return c=yield Wa(b.fa,d,e),ab(d,c,a.limit);c.delete(d);return bb(b,d,e,c,a.limit)}())}};var eb;const fb=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(let c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},gb=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){var c=a.length,d=typeof a==="string"?a.split(""):a;for(let e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};
function hb(a){var b=a.length;if(b>0){let c=Array(b);for(let d=0;d<b;d++)c[d]=a[d];return c}return[]};var kb=function(a){var b=pa("window.location.href");a==null&&(a='Unknown Error of type "null/undefined"');if(typeof a==="string")return{message:a,name:"Unknown error",lineNumber:"Not available",fileName:b,stack:"Not available"};var c=!1;try{var d=a.lineNumber||a.line||"Not available"}catch(f){d="Not available",c=!0}try{var e=a.fileName||a.filename||a.sourceURL||v.$googDebugFname||b}catch(f){e="Not available",c=!0}b=ib(a);return!c&&a.lineNumber&&a.fileName&&a.stack&&a.message&&a.name?{message:a.message,
name:a.name,lineNumber:a.lineNumber,fileName:a.fileName,stack:b}:(c=a.message,c==null&&(c=a.constructor&&a.constructor instanceof Function?'Unknown Error of type "'+(a.constructor.name?a.constructor.name:jb(a.constructor))+'"':"Unknown Error of unknown type",typeof a.toString==="function"&&Object.prototype.toString!==a.toString&&(c+=": "+a.toString())),{message:c,name:a.name||"UnknownError",lineNumber:d,fileName:e,stack:b||"Not available"})},ib=function(a,b){b||(b={});b[lb(a)]=!0;var c=a.stack||"",
d=a.cause;d&&!b[lb(d)]&&(c+="\nCaused by: ",d.stack&&d.stack.indexOf(d.toString())==0||(c+=typeof d==="string"?d:d.message+"\n"),c+=ib(d,b));a=a.errors;if(Array.isArray(a)){d=1;let e;for(e=0;e<a.length&&!(d>4);e++)b[lb(a[e])]||(c+="\nInner error "+d++ +": ",a[e].stack&&a[e].stack.indexOf(a[e].toString())==0||(c+=typeof a[e]==="string"?a[e]:a[e].message+"\n"),c+=ib(a[e],b));e<a.length&&(c+="\n... "+(a.length-e)+" more inner errors")}return c},lb=function(a){var b="";typeof a.toString==="function"&&
(b=""+a);return b+a.stack},mb=function(a){var b=Error();if(Error.captureStackTrace)Error.captureStackTrace(b,a||mb),b=String(b.stack);else{try{throw b;}catch(c){b=c}b=(b=b.stack)?String(b):null}b||(b=nb(a||arguments.callee.caller,[]));return b},nb=function(a,b){var c=[];if(fb(b,a)>=0)c.push("[...circular reference...]");else if(a&&b.length<50){c.push(jb(a)+"(");let e=a.arguments;for(let f=0;e&&f<e.length;f++){f>0&&c.push(", ");var d=void 0;d=e[f];switch(typeof d){case "object":d=d?"object":"null";
break;case "string":break;case "number":d=String(d);break;case "boolean":d=d?"true":"false";break;case "function":d=(d=jb(d))?d:"[fn]";break;default:d=typeof d}d.length>40&&(d=d.slice(0,40)+"...");c.push(d)}b.push(a);c.push(")\n");try{c.push(nb(a.caller,b))}catch(f){c.push("[exception trying to get caller]\n")}}else a?c.push("[...long stack...]"):c.push("[end]");return c.join("")},jb=function(a){if(B[a])return B[a];a=String(a);if(!B[a]){let b=/function\s+([^\(]+)/m.exec(a);B[a]=b?b[1]:"[Anonymous]"}return B[a]},
B={};var C=class{constructor(a,b){this.name=a;this.value=b}toString(){return this.name}},D=new C("OFF",Infinity),ob=new C("SHOUT",1200),pb=new C("SEVERE",1E3),qb=new C("WARNING",900),rb=new C("INFO",800),sb=new C("CONFIG",700),E=[D,ob,pb,qb,rb,sb,new C("FINE",500),new C("FINER",400),new C("FINEST",300),new C("ALL",0)],G=null,tb=class{constructor(){this.J=0;this.clear()}clear(){this.ca=Array(this.J);this.ea=-1;this.ja=!1}},ub,vb=class{constructor(a,b,c,d){this.G=void 0;this.reset(a||D,b,c,d,void 0)}reset(a,
b,c,d){this.ua=d||Date.now();this.U=a;this.Da=b;this.ka=c;this.G=void 0}getMessage(){return this.Da}},wb=function(a){return a.level?a.level:a.parent?wb(a.parent):D},xb=class{constructor(a,b=null){this.level=null;this.Aa=[];this.parent=b||null;this.children=[];this.Ca={getName:()=>a}}publish(a){for(var b=this;b;)b.Aa.forEach(c=>{c(a)}),b=b.parent}},H=function(a,b){var c=a.entries[b];if(c)return c;c=b.lastIndexOf(".");c=b.slice(0,Math.max(c,0));c=H(a,c);var d=new xb(b,c);a.entries[b]=d;c.children.push(d);
return d},yb=class{constructor(){this.entries={};var a=new xb("");a.level=sb;this.entries[""]=a}},zb,I=function(){zb||(zb=new yb);return zb},Ab=function(a,b,c){var d;if(d=a)if(d=a&&b){d=b.value;var e=a?wb(H(I(),a.getName())):D;d=d>=e.value}if(d){b=b||D;d=H(I(),a.getName());typeof c==="function"&&(c=c());ub||(ub=new tb);e=ub;a=a.getName();if(e.J>0){var f=(e.ea+1)%e.J;e.ea=f;e.ja?(e=e.ca[f],e.reset(b,c,a),a=e):(e.ja=f==e.J-1,a=e.ca[f]=new vb(b,c,a))}else a=new vb(b,c,a);a.G=void 0;d.publish(a)}},Cb=
function(a){var b=Bb;b&&Ab(b,rb,a)};function J(){this.ra=Date.now()}var Db=null;J.prototype.set=function(a){this.ra=a};J.prototype.reset=function(){this.set(Date.now())};J.prototype.get=function(){return this.ra};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
function K(a){return a.toString().indexOf("`")===-1}K(a=>a``)||K(a=>a`\0`)||K(a=>a`\n`)||K(a=>a`\u0000`);var Eb=globalThis.trustedTypes;let Fb=Eb,Gb;function Hb(){var a=null;if(!Fb)return a;try{let b=c=>c;a=Fb.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(b){}return a};var L=class{constructor(a){this.ma=a}toString(){return this.ma+""}};function Ib(a){var b;Gb===void 0&&(Gb=Hb());a=(b=Gb)?b.createHTML(a):a;return new L(a)}var Jb=new L(Eb?Eb.emptyHTML:"");function M(a){if(a instanceof L)return a.ma;throw Error("");};var Kb=class{constructor(a){this.na=a}toString(){return this.na}};function Lb(a){return new Kb(a[0])};var N=class{constructor(a){this.oa=a}toString(){return this.oa}},Mb=new N("about:invalid#zClosurez");class Nb{constructor(a){this.isValid=a}}function O(a){return new Nb(b=>b.substr(0,a.length+1).toLowerCase()===a+":")}const Ob=[O("data"),O("http"),O("https"),O("mailto"),O("ftp"),new Nb(a=>/^[^:]*([/?#]|$)/.test(a))];function Pb(a,b=Ob){if(a instanceof N)return a;for(let c=0;c<b.length;++c){let d=b[c];if(d instanceof Nb&&d.isValid(a))return new N(a)}}var Qb=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;function P(a,b){if(a instanceof L)return a;a=String(a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;");if(b==null?0:b.B)a=a.replace(/(^|[\r\n\t ]) /g,"$1&#160;");if(b==null?0:b.A)a=a.replace(/(\r\n|\n|\r)/g,"<br>");if(b==null?0:b.La)a=a.replace(/(\t+)/g,'<span style="white-space:pre">$1</span>');return Ib(a)}function Rb(a){return Q(a)}function Q(a){var b=P("");return Ib(a.map(c=>M(P(c))).join(M(b).toString()))}
const Sb=/^[a-z][a-z\d-]*$/i,Tb="APPLET BASE EMBED IFRAME LINK MATH META OBJECT SCRIPT STYLE SVG TEMPLATE".split(" ");var Ub="AREA BR COL COMMAND HR IMG INPUT KEYGEN PARAM SOURCE TRACK WBR".split(" ");const Vb=["action","formaction","href"];function Wb(a){if(!Sb.test(a))throw Error("");if(Tb.indexOf(a.toUpperCase())!==-1)throw Error("");}
function Xb(a,b,c){Wb(a);var d=`<${a}`;b&&(d+=Yb(b));Array.isArray(c)||(c=c===void 0?[]:[c]);Ub.indexOf(a.toUpperCase())!==-1?d+=">":(b=Rb(c.map(e=>e instanceof L?e:P(String(e)))),d+=">"+b.toString()+"</"+a+">");return Ib(d)}
function Yb(a){var b="",c=Object.keys(a);for(let f=0;f<c.length;f++){var d=c[f],e=a[d];if(!Sb.test(d))throw Error("");if(e!==void 0&&e!==null){if(/^on./i.test(d))throw Error("");Vb.indexOf(d.toLowerCase())!==-1&&(e instanceof N?e=e.toString():(e=String(e),e=Qb.test(e)?e:void 0,e=e||"about:invalid#zClosurez"));d=`${d}="${P(String(e))}"`;b+=" "+d}}return b};"ARTICLE SECTION NAV ASIDE H1 H2 H3 H4 H5 H6 HEADER FOOTER ADDRESS P HR PRE BLOCKQUOTE OL UL LH LI DL DT DD FIGURE FIGCAPTION MAIN DIV EM STRONG SMALL S CITE Q DFN ABBR RUBY RB RT RTC RP DATA TIME CODE VAR SAMP KBD SUB SUP I B U MARK BDI BDO SPAN BR WBR NOBR INS DEL PICTURE PARAM TRACK MAP TABLE CAPTION COLGROUP COL TBODY THEAD TFOOT TR TD TH SELECT DATALIST OPTGROUP OPTION OUTPUT PROGRESS METER FIELDSET LEGEND DETAILS SUMMARY MENU DIALOG SLOT CANVAS FONT CENTER ACRONYM BASEFONT BIG DIR HGROUP STRIKE TT".split(" ").concat(["BUTTON",
"INPUT"]);var R=function(a){this.la=a||"";Db||(Db=new J);this.ta=Db};h=R.prototype;h.ba=!0;h.O=!0;h.Y=!0;h.sa=!0;h.X=!1;h.Z=!1;
var Zb=function(a){a=new Date(a.ua);return S(a.getFullYear()-2E3)+S(a.getMonth()+1)+S(a.getDate())+" "+S(a.getHours())+":"+S(a.getMinutes())+":"+S(a.getSeconds())+"."+S(Math.floor(a.getMilliseconds()/10))},S=function(a){return a<10?"0"+a:String(a)},$b=function(a,b){a=(a.ua-b)/1E3;b=a.toFixed(3);var c=0;if(a<1)c=2;else for(;a<100;)c++,a*=10;for(;c-- >0;)b=" "+b;return b},T=function(a){R.call(this,a)};va(T,R);T.prototype.X=!0;T.prototype.ha=function(a){return a?this.R(a).toString():""};
T.prototype.R=function(a){if(!a)return Jb;switch(a.U.value){case ob.value:var b="dbg-sh";break;case pb.value:b="dbg-sev";break;case qb.value:b="dbg-w";break;case rb.value:b="dbg-i";break;default:b="dbg-f"}var c=[];c.push(this.la," ");this.O&&c.push("[",Zb(a),"] ");this.Y&&c.push("[",$b(a,this.ta.get()),"s] ");this.sa&&c.push("[",a.ka,"] ");this.Z&&c.push("[",a.U.name,"] ");c=P(c.join(""),{A:!0,B:!0});var d=Jb;if(this.X&&a.G){d=Xb("br");try{let q=kb(a.G);var e=q.fileName;e==null&&(e="");if(/^https?:\/\//i.test(e)){var f=
Pb(e,Ob)||Mb;if(f instanceof N)var g=f.oa;else throw Error("");var k=new N("view-source:"+g)}else k=Pb("sanitizedviewsrc",Ob)||Mb;var p=Rb([P("Message: "+q.message+"\nUrl: ",{A:!0,B:!0}),Xb("a",{href:k,target:"_new"},q.fileName),P("\nLine: "+q.lineNumber+"\n\nBrowser stack:\n"+q.stack+"-> [end]\n\nJS stack traversal:\n"+mb(void 0)+"-> ",{A:!0,B:!0})])}catch(q){p=P("Exception trying to expose exception! You win, we lose. "+q,{A:!0,B:!0})}d=Q([d,p])}a=P(a.getMessage(),{A:!0,B:!0});b=Xb("span",{"class":b},
Q([a,d]));return this.ba?Rb([c,b,Xb("br")]):Q([c,b])};var V=function(a){R.call(this,a)};va(V,R);V.prototype.ha=function(a){var b=[];b.push(this.la," ");this.O&&b.push("[",Zb(a),"] ");this.Y&&b.push("[",$b(a,this.ta.get()),"s] ");this.sa&&b.push("[",a.ka,"] ");this.Z&&b.push("[",a.U.name,"] ");b.push(a.getMessage());this.X&&(a=a.G,a!==void 0&&b.push("\n",a instanceof Error?a.message:String(a)));this.ba&&b.push("\n");return b.join("")};V.prototype.R=function(a){return P(V.prototype.ha(a),{A:!0,B:!0})};function ac(a=new V){a.O=!0;a.Y=!1;a.Z=!0}H(I(),"");var bc=new C("TRACE",100);E.push(new C("DEBUG",600));E.push(bc);function cc(a,b){for(let c in a)b.call(void 0,a[c],c,a)};function fc(a=document){var b,c=(b=a.querySelector)==null?void 0:b.call(a,"style[nonce]");return c==null?"":c.nonce||c.getAttribute("nonce")||""};function hc(a){if(/^(script|style)$/i.test(a.tagName))throw Error("");};var ic,jc=pa("CLOSURE_FLAGS"),kc=jc&&jc[610401301];ic=kc!=null?kc:!1;function lc(){var a=v.navigator;return a&&(a=a.userAgent)?a:""}var W;const mc=v.navigator;W=mc?mc.userAgentData||null:null;function X(a){return lc().indexOf(a)!=-1};function Y(){return ic?!!W&&!!W.platform:!1}function nc(){return X("iPhone")&&!X("iPod")&&!X("iPad")};ic&&W&&W.brands.length>0||X("Opera");ic&&W&&W.brands.length>0||X("Trident")||X("MSIE");X("Edge");!X("Gecko")||lc().toLowerCase().indexOf("webkit")!=-1&&!X("Edge")||X("Trident")||X("MSIE")||X("Edge");lc().toLowerCase().indexOf("webkit")!=-1&&!X("Edge")&&X("Mobile");Y()||X("Macintosh");Y()||X("Windows");(Y()?W.platform==="Linux":X("Linux"))||Y()||X("CrOS");Y()||X("Android");nc();X("iPad");X("iPod");nc()||X("iPad")||X("iPod");lc().toLowerCase().indexOf("kaios");var pc=function(a,b){cc(b,function(c,d){d=="style"?a.style.cssText=c:d=="class"?a.className=c:d=="for"?a.htmlFor=c:oc.hasOwnProperty(d)?a.setAttribute(oc[d],c):d.lastIndexOf("aria-",0)==0||d.lastIndexOf("data-",0)==0?a.setAttribute(d,c):a[d]=c})},oc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},qc=function(a,
b,c,d){function e(f){f&&b.appendChild(typeof f==="string"?a.createTextNode(f):f)}for(let f=d;f<c.length;f++){let g=c[f];if(!qa(g)||ra(g)&&g.nodeType>0)e(g);else{a:{if(g&&typeof g.length=="number"){if(ra(g)){d=typeof g.item=="function"||typeof g.item=="string";break a}if(typeof g==="function"){d=typeof g.item=="function";break a}}d=!1}gb(d?hb(g):g,e)}}},rc=function(a,b){b=String(b);a.contentType==="application/xhtml+xml"&&(b=b.toLowerCase());return a.createElement(b)},sc=function(a){return a.nodeType==
9?a:a.ownerDocument||a.document},Z=function(a){this.F=a||v.document||document};Z.prototype.getElementsByTagName=function(a,b){return(b||this.F).getElementsByTagName(String(a))};var tc=function(a,b){a=a.F;return(b=b&&b!="*"?String(b).toUpperCase():"")?a.querySelectorAll(b+""):a.getElementsByTagName("*")};h=Z.prototype;h.setProperties=pc;
h.da=function(a,b,c){var d=this.F,e=arguments,f=e[1],g=rc(d,String(e[0]));f&&(typeof f==="string"?g.className=f:Array.isArray(f)?g.className=f.join(" "):pc(g,f));e.length>2&&qc(d,g,e,2);return g};h.createElement=function(a){return rc(this.F,a)};h.createTextNode=function(a){return this.F.createTextNode(String(a))};h.appendChild=function(a,b){a.appendChild(b)};h.append=function(a,b){qc(sc(a),a,arguments,1)};h.canHaveChildren=function(a){if(a.nodeType!=1)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
h.removeNode=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};h.getChildren=function(a){return a.children!=void 0?a.children:Array.prototype.filter.call(a.childNodes,function(b){return b.nodeType==1})};h.isElement=function(a){return ra(a)&&a.nodeType==1};
h.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function uc(a){ua(this.aa,this);this.S=new T;this.S.O=!1;this.o=a;this.za=this.o.ownerDocument||this.o.document;this.ya=new Z(this.za);var b=Lb`
      .dbg-sev{color:#F00}
      .dbg-w{color:#C40}
      .dbg-sh{font-weight:bold;color:#000}
      .dbg-i{color:#444}
      .dbg-f{color:#999}
      .dbg-ev{color:#0A0}
      .dbg-m{color:#990}
      .logmsg{border-bottom:1px solid #CCC;padding:2px}
      .logsep{background-color: #8C8;}
      .logdiv{border:1px solid #CCC;background-color:#FCFCFC;font:medium monospace}`;a=(a=this.o)?new Z(sc(a)):eb||(eb=new Z);var c=tc(a,"HEAD")[0];if(!c){var d=tc(a,"BODY")[0];c=a.da("HEAD");d.parentNode.insertBefore(c,d)}d=a.da("STYLE");var e=fc(document);e&&d.setAttribute("nonce",e);if(b instanceof Kb)b=b.na;else throw Error("");if(v.trustedTypes)if("textContent"in d)d.textContent=b;else if(d.nodeType==3)d.data=String(b);else if(d.firstChild&&d.firstChild.nodeType==3){for(;d.lastChild!=d.firstChild;)d.removeChild(d.lastChild);
d.firstChild.data=String(b)}else{for(;e=d.firstChild;)d.removeChild(e);d.appendChild(sc(d).createTextNode(String(b)))}else d.innerHTML=b;a.appendChild(c,d);this.o.className+=" logdiv"}uc.prototype.aa=function(a){if(a){var b=this.o.scrollHeight-this.o.scrollTop-this.o.clientHeight<=100,c=this.ya.createElement("DIV");c.className="logmsg";a=this.S.R(a);c.nodeType===1&&hc(c);c.innerHTML=M(a);this.o.appendChild(c);b&&(this.o.scrollTop=this.o.scrollHeight)}};
uc.prototype.clear=function(){if(this.o){var a=this.o;a.nodeType===1&&hc(a);a.innerHTML=M(Jb)}};var wc=function(a){return m(function*(){var b=yield vc(a);if(b.length!==0){var c=a.H.scrollTop===a.H.scrollHeight;for(let g of b){b=a.V;var d=b.aa;a:{var e=g.lvl;if(!G){G={};for(let k=0,p;p=E[k];k++)G[p.value]=p,G[p.name]=p}if(e in G)e=G[e];else{for(var f=0;f<E.length;++f){let k=E[f];if(k.value<=e){e=k;break a}}e=null}}f=g.cmp.join(".");e=new vb(e,g.msg[0]||"",f,g.ts);d.call(b,e)}c&&(a.H.scrollTop=a.H.scrollHeight)}}())},xc=function(a,b){b!==(a.N!==0)&&(b?a.N=setInterval(()=>m(function*(){try{yield a.background.hello()}catch(c){console.debug("Failed to send hello to keep background alive",
c)}}()),25E3):(clearInterval(a.N),a.N=0))},vc=function(a){return m(function*(){var b=a.C.ga===-1||a.C.T===-1;var c=b?{}:{id:new Ya(IDBKeyRange.lowerBound(a.C.T,!0))};c=yield a.Ba.query(c);if(c.length===0)return c;b&&(a.C.ga=c[0].id);a.C.T=c[c.length-1].id;return c}())},Bc=class{constructor(){var a=yc;this.va=zc;this.Ba=a;this.H=document.querySelector("#log-buffer");this.V=new uc(this.H);this.N=0;this.C={ga:-1,T:-1};this.qa=0;this.background=Ac(this.va);ac(this.V.S)}initialize(){var a=this;return m(function*(){yield wc(a);
a.qa===0&&(a.qa=setInterval(()=>{wc(a)},500));var b=document.querySelector("#clear-log");b&&(b.onclick=()=>{a.V.clear()});var c=document.querySelector("#keep-alive-checkbox");c&&(c.onchange=()=>{xc(a,c.checked)});b=document.querySelectorAll("[data-i18n]");for(let d of b)b=d.getAttribute("data-i18n"),d.textContent=chrome.i18n.getMessage(b)||"PLACEHOLDER"}())}};var Cc=class{constructor(){var a=void 0,b=void 0;this.promise=new Promise((c,d)=>{a=c;b=d});this.resolve=a;this.reject=b}},Dc=class extends x{constructor(a,b="One or more errors occurred."){super(1,xa,b);this.errors=a;Object.setPrototypeOf(this,new.target.prototype)}flatten(){for(var a=[],b=[this.errors.slice(0)];b.length!==0;){let c=b[0];for(;c.length!==0;){let d=c.shift();if(d instanceof Dc){b.unshift(d.errors.slice(0));break}else a.push(d)}b[0]===c&&b.shift()}return new Dc(a,this.message)}};function Ec(a,b,...c){return m(function*(){var d=new Cc,e={magic:91556947316803,host:a!==null&&typeof a==="number"?"*":a,method:b,args:c},f=g=>{var k=chrome.runtime.lastError;k?d.reject(new x(1,za,`Operation '${String(b)}' failed. ${k.message||"Undefined error."}`)):g.error!==void 0?d.reject(Fc(g.error)):d.resolve(g.result)};a!==null&&typeof a==="number"?chrome.tabs.sendMessage(a,e,f):chrome.runtime.sendMessage(e,f);return d.promise}())}
function Fc(a){switch(a.type){case 0:return a.object;case 1:return Error(a.message);case 2:return new x(a.code,Da(a.category),a.message);case 3:return new Dc(a.errors.map(Fc),a.message)}};function Gc(a){return m(function*(){return new Promise(b=>{setTimeout(()=>{b(void 0)},a)})}())};var Ac=function(a){var b=Object.values(wa);for(let [d,e]of a.pa){let f=d;var c=e;if(b.every(g=>f.has(g)))return c}c={};for(let d of b)Object.defineProperty(c,d,{value:(...e)=>a.invoke(d,...e),writable:!1});a.pa.set(new Set(b),c);return c};const zc=new class{constructor(a="*"){this.host=a;this.events=new Map;this.pa=new Map}invoke(a,...b){var c=this;return m(function*(){return Ec(c.host,a,...b)}())}},Hc=Ac(zc),cb=new Xa,yc=new db,Bb=H(I(),"Log Script").Ca;
function Ic(){m(function*(){Cb("Initializing...");yield cb.initialize();for(let b=1;b<=10;++b)try{yield Hc.hello();break}catch(c){if(b>=10){var a=Bb;a&&Ab(a,pb,`Failed to communicate with background page after ${b} attempts. ${c.message}`);throw c;}yield Gc(100+(15<<b))}yield(new Bc).initialize();Cb("Done.")}())}document.addEventListener("DOMContentLoaded",()=>{Cb("Handling DOMContentLoaded...");Ic()});
