'use strict';var aa=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},ca=ba(this),h=function(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=
0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&aa(c,a,{configurable:!0,writable:!0,value:b})}},da=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},k=function(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})};h("Symbol.asyncIterator",function(a){return a?a:Symbol("Symbol.asyncIterator")});
var fa=function(a){var b=a[Symbol.asyncIterator];if(b!==void 0)a=b.call(a);else{b=ea;var c=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(c)a=c.call(a);else if(typeof a.length=="number")a={next:da(a)};else throw Error(String(a)+" is not an iterable or ArrayLike");a=new b(a)}return a},ea=function(a){function b(c){return Promise.resolve(c.value).then(function(d){return{value:d,done:!!c.done}})}this[Symbol.asyncIterator]=function(){return this};this[Symbol.iterator]=function(){return a};
this.next=function(c){return(new Promise(function(d){d(a.next(c))})).then(b)};this["throw"]=function(c){return(new Promise(function(d,e){var f=a["throw"];f!==void 0?d(f.call(a,c)):(d=a["return"],d!==void 0&&d.call(a),e(new TypeError("no `throw` method")))})).then(b)};a["return"]!==void 0&&(this["return"]=function(c){return(new Promise(function(d){d(a["return"](c))})).then(b)})},l=function(a,b){this.action=a;this.value=b},ha=function(a,b,c,d){this.method=a;this.o=b;this.resolve=c;this.reject=d},ia=
function(a){this.frame=a;this.next=null},n=function(){this.H=this.u=null};n.prototype.isEmpty=function(){return this.u===null};n.prototype.first=function(){if(this.u)return this.u.frame;throw Error("no frames in executionQueue");};n.prototype.drop=function(){this.u&&(this.u=this.u.next,this.u||(this.H=null))};n.prototype.enqueue=function(a){a=new ia(a);this.H?this.H.next=a:this.u=a;this.H=a};
var q=function(a){this.U=a;this.j=null;this.i=new n;this[Symbol.asyncIterator]=function(){return this};var b=this;this.fa=function(c){var d=b.i.first();c.done===!0?(b.j=null,d.method!=="return"&&(d.method="next",d.o=c.value)):(d.resolve({value:c.value,done:!1}),b.i.drop());p(b)};this.ea=function(c){ja(b,c)};this.B=function(c){ka(b,c)}},r=function(a,b,c){return new Promise(function(d,e){var f=a.i.isEmpty();a.i.enqueue(new ha(b,c,d,e));f&&p(a)})};q.prototype.next=function(a){return r(this,"next",a)};
q.prototype.return=function(a){return r(this,"return",new l(0,a))};q.prototype.throw=function(a){return r(this,"throw",a)};
var p=function(a){if(!a.i.isEmpty())try{a.j?la(a):ma(a)}catch(b){ka(a,b)}},ma=function(a){var b=a.i.first();try{var c=a.U[b.method](b.o);if(c.value instanceof l)switch(c.value.action){case 0:Promise.resolve(c.value.value).then(function(d){b.resolve({value:d,done:c.done});a.i.drop();p(a)},function(d){b.reject(d);a.i.drop();p(a)}).catch(a.B);break;case 1:a.j=fa(c.value.value);b.method="next";b.o=void 0;p(a);break;case 2:Promise.resolve(c.value.value).then(function(d){b.method="next";b.o=d;p(a)},function(d){b.method=
"throw";b.o=d;p(a)}).catch(a.B);break;default:throw Error("Unrecognized AsyncGeneratorWrapper$ActionEnum");}else b.resolve(c),a.i.drop(),p(a)}catch(d){b.reject(d),a.i.drop(),p(a)}},la=function(a){if(!a.j)throw Error("no delegate to perform execution");var b=a.i.first();if(b.method in a.j)try{var c=b.o;c instanceof l&&(c=c.value);a.j[b.method](c).then(a.fa,a.ea).catch(a.B)}catch(d){ja(a,d)}else if(b.method==="throw")if(c=a.j,a.j=null,"return"in c)try{Promise.resolve(c["return"]()).then(function(){b.o=
new TypeError("The iterator does not provide a 'throw' method");p(a)},function(d){b.o=d;p(a)}).catch(a.B)}catch(d){b.o=d,p(a)}else b.o=new TypeError("The iterator does not provide a 'throw' method"),p(a);else a.j=null,p(a)},ja=function(a,b){var c=a.i.first();a.j=null;c.method="throw";c.o=b;p(a)},ka=function(a,b){a.i.isEmpty()||(a.i.first().reject(b),a.i.drop());a.j&&"return"in a.j&&(a.j["return"](void 0),a.j=null);a.U["return"](void 0);p(a)};
h("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});h("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&c.push([d,b[d]]);return c}});
h("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&c.push(b[d]);return c}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var na=this||self,oa=function(a,b,c){return a.call.apply(a.bind,arguments)},pa=function(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},t=function(a,b,c){t=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?oa:pa;return t.apply(null,arguments)},ra=function(a,
b){function c(){}c.prototype=b.prototype;a.ta=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ra=function(d,e,f){for(var g=Array(arguments.length-2),m=2;m<arguments.length;m++)g[m-2]=arguments[m];return b.prototype[e].apply(d,g)}};var va=function(a){switch(a){case u.name:return u;case v.name:return v;case w.name:return w;case sa.name:return sa;case ta.name:return ta;default:let b=ua.get(a);b||(b=new x(a),ua.set(a,b));return b}},x=class{constructor(a){this.name=a}toString(){return this.name}},ua=new Map,u=new x("async"),v=new x("generic"),w=new x("runtime"),sa=new x("system"),ta=new x("crypto"),y=class extends Error{constructor(a,b,c){super(c);this.code=a;this.category=b;Object.setPrototypeOf(this,new.target.prototype)}toString(){return`${this.category}:${this.code} (${this.message||
"Undefined error."})`}};function z(a){throw new y(416,v,a);};/*

 ISC License (ISC)
 Copyright (c) 2016, Jake Archibald <jaffathecake\@gmail.com>

 Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee
 is hereby granted, provided that the above copyright notice and this permission notice appear in all
 copies.

 THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS
 SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
 AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
 OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
 SOFTWARE.
*/
var xa=a=>(wa||(wa=[IDBDatabase,IDBObjectStore,IDBIndex,IDBCursor,IDBTransaction])).some(b=>a instanceof b);let wa,ya;const za=new WeakMap,A=new WeakMap,Aa=new WeakMap,B=new WeakMap;var C=new WeakMap;function Ba(a){var b=new Promise((c,d)=>{var e=()=>{a.removeEventListener("success",f);a.removeEventListener("error",g)},f=()=>{c(D(a.result));e()},g=()=>{d(a.error);e()};a.addEventListener("success",f);a.addEventListener("error",g)});b.then(c=>{c instanceof IDBCursor&&za.set(c,a)}).catch(()=>{});C.set(b,a);return b}
function Ca(a){if(!A.has(a)){var b=new Promise((c,d)=>{var e=()=>{a.removeEventListener("complete",f);a.removeEventListener("error",g);a.removeEventListener("abort",g)},f=()=>{c();e()},g=()=>{d(a.error||new DOMException("AbortError","AbortError"));e()};a.addEventListener("complete",f);a.addEventListener("error",g);a.addEventListener("abort",g)});A.set(a,b)}}
let E={get(a,b,c){if(a instanceof IDBTransaction){if(b==="done")return A.get(a);if(b==="objectStoreNames")return a.objectStoreNames||Aa.get(a);if(b==="store")return c.objectStoreNames[1]?void 0:c.objectStore(c.objectStoreNames[0])}return D(a[b])},set(a,b,c){a[b]=c;return!0},has(a,b){return a instanceof IDBTransaction&&(b==="done"||b==="store")?!0:b in a}};
function Da(a){return a!==IDBDatabase.prototype.transaction||"objectStoreNames"in IDBTransaction.prototype?(ya||(ya=[IDBCursor.prototype.advance,IDBCursor.prototype.continue,IDBCursor.prototype.continuePrimaryKey])).includes(a)?function(...b){a.apply(C.get(this),b);return D(za.get(this))}:function(...b){return D(a.apply(C.get(this),b))}:function(b,...c){c=a.call(C.get(this),b,...c);Aa.set(c,b.sort?b.sort():[b]);return D(c)}}
function D(a){if(a instanceof IDBRequest)return Ba(a);if(B.has(a))return B.get(a);if(typeof a==="function")var b=Da(a);else a instanceof IDBTransaction&&Ca(a),b=xa(a)?new Proxy(a,E):a;b!==a&&(B.set(a,b),C.set(b,a));return b};const Ea=["get","getKey","getAll","getAllKeys","count"],Fa=["put","add","delete","clear"],F=new Map;
function Ga(a,b){if(a instanceof IDBDatabase&&!(b in a)&&typeof b==="string"){if(F.get(b))return F.get(b);var c=b.replace(/FromIndex$/,""),d=b!==c,e=Fa.includes(c);if(c in(d?IDBIndex:IDBObjectStore).prototype&&(e||Ea.includes(c)))return a=function(f,...g){var m=this;return k(function*(){var qa=m.transaction(f,e?"readwrite":"readonly"),T=qa.store;d&&(T=T.index(g.shift()));return(yield Promise.all([T[c](...g),e&&qa.done]))[0]}())},F.set(b,a),a}}
E=(a=>Object.assign({},a,{get:(b,c,d)=>Ga(b,c)||a.get(b,c,d),has:(b,c)=>!!Ga(b,c)||a.has(b,c)}))(E);function Ha({blocked:a,upgrade:b,sa:c,va:d}={}){var e=indexedDB.open("log-db",1),f=D(e);b&&e.addEventListener("upgradeneeded",g=>{b(D(e.result),g.oldVersion,g.newVersion,D(e.transaction))});a&&e.addEventListener("blocked",()=>a());f.then(g=>{d&&g.addEventListener("close",()=>d());c&&g.addEventListener("versionchange",()=>c())}).catch(()=>{});return f};var Ja=function(a,b,c){k(function*(){c.ct=a.context;c.ep=Ia;yield b.add(c)}())},Ka=class{constructor(){this.context="popup";this.capacity=1E3;this.ia=void 0;this.db=null}initialize(){var a=this;return k(function*(){a.db&&z("Log database is already initialized.");var b=Object.assign({},a.ia);b.upgrade===void 0&&(b.upgrade=c=>{a.createObjectStore(c)});a.db=yield Ha(b);a.trim()}())}createObjectStore(a){a.objectStoreNames.contains("logs")||(a=a.createObjectStore("logs",{keyPath:"id",autoIncrement:!0}),
a.createIndex("ts","ts",{unique:!1}),a.createIndex("lvl","lvl",{unique:!1}),a.createIndex("cmp","cmp",{unique:!1}),a.createIndex("ep","ep",{unique:!1}),a.createIndex("ct","ct",{unique:!1}))}trim(){var a=this;return k(function*(){var b=a.db.transaction("logs","readwrite"),c=b.objectStore("logs");if(!(a.capacity>=(yield c.count()))){var d=yield c.openKeyCursor(null,"prev");if(d!==null)return yield c.delete(IDBKeyRange.upperBound(d.primaryKey-a.capacity,!1)),b.done}}())}write(a){var b=this;return k(function*(){b.db||
z("Log database is not initialized.");if(!Array.isArray(a)||a.length!==0){var c=b.db.transaction("logs","readwrite"),d=c.objectStore("logs");Array.isArray(a)?a.forEach(e=>{Ja(b,d,e)}):Ja(b,d,a);c.commit();return c.done}}())}range(a,b,c="next"){var d=this;return function(){return new q(function*(){d.db||z("Log database is not initialized.");var e=d.db.transaction("logs","readonly"),f=e.objectStore("logs");a==="id"?f=yield new l(2,f.openCursor(b,c)):(f=f.index(a),f=yield new l(2,f.openCursor(b,c)));
for(;f;)yield new l(0,f.value),f=yield new l(2,f.continue());return new l(0,e.done)}())}()}},Ia=Date.now();function La(a,b,c){a&&setTimeout(c)}var Na=class{constructor(){this.ma=Ma;this.I=void 0;this.buffer=null}write(a){var b=this;return k(function*(){var c=!1;b.buffer||(b.buffer=[],c=!0);Array.isArray(a)?b.buffer.push(...a):b.buffer.push(a);b.I&&b.I(c,b.buffer.length,()=>b.flush())}())}flush(){var a=this;return k(function*(){if(a.buffer){var b=a.buffer;a.buffer=null;yield a.ma.write(b)}}())}};var G=class{constructor(a,b){this.name=a;this.value=b}toString(){return this.name}},H=new G("OFF",Infinity),I=new G("SEVERE",1E3),J=new G("WARNING",900),Oa=new G("INFO",800),K=new G("CONFIG",700),Pa=new G("ALL",0),L=[H,new G("SHOUT",1200),I,J,Oa,K,new G("FINE",500),new G("FINER",400),new G("FINEST",300),Pa],M=null,Qa=function(a){if(!M){M={};for(let b=0,c;c=L[b];b++)M[c.value]=c,M[c.name]=c}if(a in M)return M[a];for(let b=0;b<L.length;++b){let c=L[b];if(c.value<=a)return c}return null},Ra=class{constructor(){this.C=
0;this.clear()}clear(){this.S=Array(this.C);this.T=-1;this.V=!1}},N,Sa=class{constructor(a,b,c){this.F=void 0;this.reset(a||H,b,c,void 0,void 0)}reset(a,b,c,d){this.O=d||Date.now();this.G=a;this.ha=b;this.J=c;this.F=void 0}getMessage(){return this.ha}},Ta=function(a){return a.level?a.level:a.parent?Ta(a.parent):H},Ua=class{constructor(a,b=null){this.level=null;this.v=[];this.parent=b||null;this.children=[];this.X={getName:()=>a}}K(a){for(var b=this;b;)b.v.forEach(c=>{c(a)}),b=b.parent}},O=function(a,
b){var c=a.entries[b];if(c)return c;c=b.lastIndexOf(".");c=b.slice(0,Math.max(c,0));c=O(a,c);var d=new Ua(b,c);a.entries[b]=d;c.children.push(d);return d},Va=class{constructor(){this.entries={};var a=new Ua("");a.level=K;this.entries[""]=a}},P,Q=function(){P||(P=new Va);return P},Wa=function(a){var b=R;b&&O(Q(),b.getName()).v.push(a)},S=function(a){var b=R;b&&(O(Q(),b.getName()).level=a)},Xa=function(){var a=R;return a?O(Q(),a.getName()).level:null},U=function(a,b,c){var d;if(d=a)if(d=a&&b){d=b.value;
var e=a?Ta(O(Q(),a.getName())):H;d=d>=e.value}if(d){b=b||H;d=O(Q(),a.getName());typeof c==="function"&&(c=c());N||(N=new Ra);e=N;a=a.getName();if(e.C>0){var f=(e.T+1)%e.C;e.T=f;e.V?(e=e.S[f],e.reset(b,c,a),a=e):(e.V=f==e.C-1,a=e.S[f]=new Sa(b,c,a))}else a=new Sa(b,c,a);a.F=void 0;d.K(a)}};function Ya(){var a=Za,b;b||(b=c=>c.split("/").filter(d=>d));return c=>{a.write({ts:c.O,lvl:c.G.value,cmp:b(c.J),msg:[c.getMessage()]})}};function V(){this.aa=Date.now()}var $a=null;V.prototype.set=function(a){this.aa=a};V.prototype.reset=function(){this.set(Date.now())};V.prototype.get=function(){return this.aa};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
function W(a){return a.toString().indexOf("`")===-1}W(a=>a``)||W(a=>a`\0`)||W(a=>a`\n`)||W(a=>a`\u0000`);"ARTICLE SECTION NAV ASIDE H1 H2 H3 H4 H5 H6 HEADER FOOTER ADDRESS P HR PRE BLOCKQUOTE OL UL LH LI DL DT DD FIGURE FIGCAPTION MAIN DIV EM STRONG SMALL S CITE Q DFN ABBR RUBY RB RT RTC RP DATA TIME CODE VAR SAMP KBD SUB SUP I B U MARK BDI BDO SPAN BR WBR NOBR INS DEL PICTURE PARAM TRACK MAP TABLE CAPTION COLGROUP COL TBODY THEAD TFOOT TR TD TH SELECT DATALIST OPTGROUP OPTION OUTPUT PROGRESS METER FIELDSET LEGEND DETAILS SUMMARY MENU DIALOG SLOT CANVAS FONT CENTER ACRONYM BASEFONT BIG DIR HGROUP STRIKE TT".split(" ").concat(["BUTTON",
"INPUT"]);var X=function(a){this.ja=a||"";$a||($a=new V);this.la=$a};X.prototype.R=!0;X.prototype.N=!0;X.prototype.ca=!0;X.prototype.ka=!0;X.prototype.ba=!1;X.prototype.da=!1;var Y=function(a){return a<10?"0"+a:String(a)},ab=function(a){X.call(this,a)};ra(ab,X);
var bb=function(a,b){var c=[];c.push(a.ja," ");if(a.N){var d=new Date(b.O);c.push("[",Y(d.getFullYear()-2E3)+Y(d.getMonth()+1)+Y(d.getDate())+" "+Y(d.getHours())+":"+Y(d.getMinutes())+":"+Y(d.getSeconds())+"."+Y(Math.floor(d.getMilliseconds()/10)),"] ")}if(a.ca){d=c.push;var e=a.la.get();e=(b.O-e)/1E3;let f=e.toFixed(3),g=0;if(e<1)g=2;else for(;e<100;)g++,e*=10;for(;g-- >0;)f=" "+f;d.call(c,"[",f,"s] ")}a.ka&&c.push("[",b.J,"] ");a.da&&c.push("[",b.G.name,"] ");c.push(b.getMessage());a.ba&&(b=b.F,
b!==void 0&&c.push("\n",b instanceof Error?b.message:String(b)));a.R&&c.push("\n");return c.join("")};function cb(a=new ab){a.N=!0;a.ca=!1;a.da=!0}var fb=class{constructor(){this.name="Popup Script";this.target=O(Q(),"Popup Script").X}log(a,b){U(this.target,a!=null?a:db,b)}error(a){U(this.target,I,a)}warn(a){U(this.target,J,a)}info(a){U(this.target,Oa,a)}debug(a){U(this.target,db,a)}trace(a){U(this.target,eb,a)}},R=O(Q(),"").X,db=new G("DEBUG",600),eb=new G("TRACE",100);L.push(db);L.push(eb);var gb=class{constructor(){var a=void 0,b=void 0;this.promise=new Promise((c,d)=>{a=c;b=d});this.resolve=a;this.reject=b}},hb=class extends y{constructor(a,b="One or more errors occurred."){super(1,u,b);this.errors=a;Object.setPrototypeOf(this,new.target.prototype)}flatten(){for(var a=[],b=[this.errors.slice(0)];b.length!==0;){let c=b[0];for(;c.length!==0;){let d=c.shift();if(d instanceof hb){b.unshift(d.errors.slice(0));break}else a.push(d)}b[0]===c&&b.shift()}return new hb(a,this.message)}};var ib=class{constructor(){this.v=[]}subscribe(a){this.v.push(a)}unsubscribe(a){a=this.v.indexOf(a);if(a===-1)return!1;this.v.splice(a,1);return!0}K(...a){var b=[],c=this.v.slice(0);for(let d of c)b.push(d(...a))}};function jb(a,b,...c){return k(function*(){var d=new gb,e={magic:91556947316803,host:a!==null&&typeof a==="number"?"*":a,method:b,args:c},f=g=>{var m=chrome.runtime.lastError;m?d.reject(new y(1,w,`Operation '${String(b)}' failed. ${m.message||"Undefined error."}`)):g.error!==void 0?d.reject(kb(g.error)):d.resolve(g.result)};a!==null&&typeof a==="number"?chrome.ua.sendMessage(a,e,f):chrome.runtime.sendMessage(e,f);return d.promise}())}
function kb(a){switch(a.type){case 0:return a.object;case 1:return Error(a.message);case 2:return new y(a.code,va(a.category),a.message);case 3:return new hb(a.errors.map(kb),a.message)}};var mb=function(){var a=lb,b=a.events.get("log/level:change");if(!b){let c=chrome.runtime.connect({name:"log/level:change"}),d=new ib;b={port:c,source:d,Z:[]};c.onMessage.addListener(e=>{e=Array.isArray(e)?e:[e];var f=b.Z.shift();f?f.resolve(e.length>1?e:e[0]):d.K(...e)});a.events.set("log/level:change",b)}return b},nb=function(){var a=mb(),b=new gb;a.Z.push(b);a.port.postMessage({});return b.promise},ob=class{constructor(){this.host="*";this.events=new Map;this.Y=new Map}invoke(a,...b){var c=this;
return k(function*(){return jb(c.host,a,...b)}())}};function pb(a){return k(function*(){return new Promise(b=>{setTimeout(()=>{b(void 0)},a)})}())};var qb=function(){t(this.P,this);this.A=new ab;this.A.N=!1;this.A.ba=!1;this.A.R=!1;this.ga={}};qb.prototype.P=function(a){function b(e){if(e){if(e.value>=I.value)return"error";if(e.value>=J.value)return"warn";if(e.value>=K.value)return"log"}return"debug"}if(!this.ga[a.J]){var c=bb(this.A,a),d=rb;if(d){let e=b(a.G);sb(d,e,c,a.F)}}};var rb=na.console,sb=function(a,b,c,d){if(a[b])a[b](c,d===void 0?"":d);else a.log(c,d===void 0?"":d)};const lb=new ob,tb=function(){var a=lb,b=Object.values({na:"hello",oa:"getQuirks",pa:"updateQuirks",qa:"uiEvent"});for(let [d,e]of a.Y){let f=d;var c=e;if(b.every(g=>f.has(g)))return c}c={};for(let d of b)Object.defineProperty(c,d,{value:(...e)=>a.invoke(d,...e),writable:!1});a.Y.set(new Set(b),c);return c}(),Ma=new Ka,Za=new Na;(function(){S(Pa);var a=new qb;cb(a.A);Wa(b=>{var c=b.G;c&&c.value>=J.value&&a.P(b)});Wa(Ya())})();const Z=new fb;
function ub(){k(function*(){Z.debug("Initializing...");yield Ma.initialize();yield Za.flush();Za.I=La;var a=document.querySelectorAll("[data-i18n]");for(var b of a)a=b.getAttribute("data-i18n"),b.textContent=chrome.i18n.getMessage(a)||"PLACEHOLDER";for(b=1;b<=10;++b)try{yield tb.hello();break}catch(d){if(b>=10)throw Z.error(`Failed to communicate with background page after ${b} attempts. ${d.message}`),d;yield pb(100+(15<<b))}b=yield nb();b=Qa(b);S(b);var c;Z.warn(`Log level is set to ${(c=Xa())==
null?void 0:c.name}.`);mb().source.subscribe(d=>{d=Qa(d);S(d);var e;Z.warn(`Log level is set to ${(e=Xa())==null?void 0:e.name}.`)});try{yield tb.uiEvent({event:"Popup Load"})}catch(d){Z.warn(`Failed to send 'Popup Load' event notification. ${d.message}`)}Z.debug("Done.")}())}document.addEventListener("DOMContentLoaded",()=>{Z.trace("Handling DOMContentLoaded...");ub()});const vb=document.querySelector("#templates");
vb==null||vb.addEventListener("mdl-componentupgrading",a=>{Z.info("Handling mdl-componentupgrading...");a.preventDefault()});
