'use strict';var f=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},h=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},k=h(this),l=function(a,b){if(b)a:{var c=k;a=a.split(".");for(var d=
0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&f(c,a,{configurable:!0,writable:!0,value:b})}},m=function(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function g(r){r.done?d(r.value):Promise.resolve(r.value).then(b,c).then(g,e)}g(a.next())})};l("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&c.push([d,b[d]]);return c}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var n=class{constructor(a,b){this.name=a;this.value=b}toString(){return this.name}},p=new n("OFF",Infinity),q=new n("SEVERE",1E3),t=new n("WARNING",900),u=new n("INFO",800),v=new n("CONFIG",700),w=[p,new n("SHOUT",1200),q,t,u,v,new n("FINE",500),new n("FINER",400),new n("FINEST",300),new n("ALL",0)],x=class{constructor(){this.i=0;this.clear()}clear(){this.j=Array(this.i);this.o=-1;this.u=!1}},y,z=class{constructor(a,b,c){this.reset(a||p,b,c,void 0,void 0)}reset(a,b,c,d){d||Date.now();this.B=b}getMessage(){return this.B}},
A=function(a){return a.level?a.level:a.parent?A(a.parent):p},B=class{constructor(a,b=null){this.level=null;this.v=[];this.parent=b||null;this.children=[];this.A={getName:()=>a}}publish(a){for(var b=this;b;)b.v.forEach(c=>{c(a)}),b=b.parent}},C=function(a,b){var c=a.entries[b];if(c)return c;c=b.lastIndexOf(".");c=b.slice(0,Math.max(c,0));c=C(a,c);var d=new B(b,c);a.entries[b]=d;c.children.push(d);return d},D=class{constructor(){this.entries={};var a=new B("");a.level=v;this.entries[""]=a}},E,F=function(){E||
(E=new D);return E},G=function(a,b,c){var d;if(d=a)if(d=a&&b){d=b.value;var e=a?A(C(F(),a.getName())):p;d=d>=e.value}if(d){b=b||p;d=C(F(),a.getName());typeof c==="function"&&(c=c());y||(y=new x);e=y;a=a.getName();if(e.i>0){var g=(e.o+1)%e.i;e.o=g;e.u?(e=e.j[g],e.reset(b,c,a),a=e):(e.u=g==e.i-1,a=e.j[g]=new z(b,c,a))}else a=new z(b,c,a);d.publish(a)}};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
function H(a){return a.toString().indexOf("`")===-1}H(a=>a``)||H(a=>a`\0`)||H(a=>a`\n`)||H(a=>a`\u0000`);"ARTICLE SECTION NAV ASIDE H1 H2 H3 H4 H5 H6 HEADER FOOTER ADDRESS P HR PRE BLOCKQUOTE OL UL LH LI DL DT DD FIGURE FIGCAPTION MAIN DIV EM STRONG SMALL S CITE Q DFN ABBR RUBY RB RT RTC RP DATA TIME CODE VAR SAMP KBD SUB SUP I B U MARK BDI BDO SPAN BR WBR NOBR INS DEL PICTURE PARAM TRACK MAP TABLE CAPTION COLGROUP COL TBODY THEAD TFOOT TR TD TH SELECT DATALIST OPTGROUP OPTION OUTPUT PROGRESS METER FIELDSET LEGEND DETAILS SUMMARY MENU DIALOG SLOT CANVAS FONT CENTER ACRONYM BASEFONT BIG DIR HGROUP STRIKE TT".split(" ").concat(["BUTTON",
"INPUT"]);var K=class{constructor(a){this.name=a;this.target=C(F(),a).A}log(a,b){G(this.target,a!=null?a:I,b)}error(a){G(this.target,q,a)}warn(a){G(this.target,t,a)}info(a){G(this.target,u,a)}debug(a){G(this.target,I,a)}trace(a){G(this.target,J,a)}};C(F(),"");var I=new n("DEBUG",600),J=new n("TRACE",100);w.push(I);w.push(J);const L=new K("AC/BlockPresenter");
var M=function(a){document.title="Access blocked";document.getElementById("heading").textContent="Access blocked";if(a.url){a=a.url;var b=a.startsWith("http://"),c=a.startsWith("https://");b||c?(b=b?7:8,c=a.indexOf("/",b),a=c===-1?a.substring(b):a.substring(b,c),b=a.indexOf(":"),a=b>0?a.substring(0,b):a):a=void 0}else a=void 0;document.getElementById("message").textContent=`Access to ${a||"this location"} is blocked by your organization.`},N=function(a){return m(function*(){L.debug(()=>`Presenting for '${a.url}'.`);
M(a);var b=document.querySelectorAll("[data-i18n]");for(let c of b)b=c.getAttribute("data-i18n"),c.textContent=chrome.i18n.getMessage(b)||"PLACEHOLDER"}())},O=class{constructor(a){this.url=a}};var aa=function(a){switch(a){case P.name:return P;case Q.name:return Q;case R.name:return R;case S.name:return S;case T.name:return T;default:let b=U.get(a);b||(b=new V(a),U.set(a,b));return b}},V=class{constructor(a){this.name=a}toString(){return this.name}},U=new Map,P=new V("async"),Q=new V("generic"),R=new V("runtime"),S=new V("system"),T=new V("crypto"),W=class extends Error{constructor(a,b,c){super(c);this.code=a;this.category=b;Object.setPrototypeOf(this,new.target.prototype)}toString(){return`${this.category}:${this.code} (${this.message||
"Undefined error."})`}};var ba=class{constructor(){var a=void 0,b=void 0;this.promise=new Promise((c,d)=>{a=c;b=d});this.resolve=a;this.reject=b}},X=class extends W{constructor(a,b="One or more errors occurred."){super(1,P,b);this.errors=a;Object.setPrototypeOf(this,new.target.prototype)}flatten(){for(var a=[],b=[this.errors.slice(0)];b.length!==0;){let c=b[0];for(;c.length!==0;){let d=c.shift();if(d instanceof X){b.unshift(d.errors.slice(0));break}else a.push(d)}b[0]===c&&b.shift()}return new X(a,this.message)}};function ca(){var a=[];return m(function*(){var b=new ba;chrome.runtime.sendMessage({magic:91556947316803,host:"AC/NavigationController",method:"getDetails",args:a},c=>{var d=chrome.runtime.lastError;d?b.reject(new W(1,R,`Operation 'getDetails' failed. ${d.message||"Undefined error."}`)):c.error!==void 0?b.reject(Y(c.error)):b.resolve(c.result)});return b.promise}())}
function Y(a){switch(a.type){case 0:return a.object;case 1:return Error(a.message);case 2:return new W(a.code,aa(a.category),a.message);case 3:return new X(a.errors.map(Y),a.message)}};const Z=new K("AC/BlockScript");function da(){m(function*(){Z.debug("Initializing...");try{var a=yield ca()}catch(c){Z.error(`Failed to get details. ${c}`)}var b;yield N(new O((b=a)==null?void 0:b.url));Z.debug("Done.")}())}document.addEventListener("DOMContentLoaded",()=>{Z.debug("Handling DOMContentLoaded...");da()});
