'use strict';var m=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},r=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},t=r(this),w=function(a,b){if(b)a:{var c=t;a=a.split(".");for(var d=
0;d<a.length-1;d++){var f=a[d];if(!(f in c))break a;c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&m(c,a,{configurable:!0,writable:!0,value:b})}},x=function(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,f){function h(k){k.done?d(k.value):Promise.resolve(k.value).then(b,c).then(h,f)}h(a.next())})};w("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&c.push([d,b[d]]);return c}});const z={200:"OK",201:"Created",202:"Accepted",203:"Non-Authoritative Information",204:"No Content",205:"Reset Content",206:"Partial Content",300:"Multiple Choices",301:"Moved Permanently",302:"Found",303:"See Other",304:"Not Modified",305:"Use Proxy",306:"Unused",307:"Temporary Redirect",400:"Bad Request",401:"Unauthorized",402:"Payment Required",403:"Forbidden",404:"Not Found",405:"Method Not Allowed",406:"Not Acceptable",407:"Proxy Authentication Required",408:"Request Timeout",409:"Conflict",
410:"Gone",411:"Length Required",412:"Precondition Required",413:"Request Entry Too Large",414:"Request-URI Too Long",415:"Unsupported Media Type",416:"Requested Range Not Satisfiable",417:"Expectation Failed",418:"I'm a teapot",429:"Too Many Requests",500:"Internal Server Error",501:"Not Implemented",502:"Bad Gateway",503:"Service Unavailable",504:"Gateway Timeout",505:"HTTP Version Not Supported"};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var A=class{constructor(a,b){this.name=a;this.value=b}toString(){return this.name}},B=new A("OFF",Infinity),C=new A("SEVERE",1E3),D=new A("WARNING",900),E=new A("INFO",800),F=new A("CONFIG",700),G=[B,new A("SHOUT",1200),C,D,E,F,new A("FINE",500),new A("FINER",400),new A("FINEST",300),new A("ALL",0)],aa=class{constructor(){this.i=0;this.clear()}clear(){this.o=Array(this.i);this.u=-1;this.v=!1}},H,J=class{constructor(a,b,c){this.reset(a||B,b,c,void 0,void 0)}reset(a,b,c,d){d||Date.now();this.I=b}getMessage(){return this.I}},
K=function(a){return a.level?a.level:a.parent?K(a.parent):B},L=class{constructor(a,b=null){this.level=null;this.B=[];this.parent=b||null;this.children=[];this.G={getName:()=>a}}publish(a){for(var b=this;b;)b.B.forEach(c=>{c(a)}),b=b.parent}},M=function(a,b){var c=a.entries[b];if(c)return c;c=b.lastIndexOf(".");c=b.slice(0,Math.max(c,0));c=M(a,c);var d=new L(b,c);a.entries[b]=d;c.children.push(d);return d},ba=class{constructor(){this.entries={};var a=new L("");a.level=F;this.entries[""]=a}},N,O=function(){N||
(N=new ba);return N},P=function(a,b,c){var d;if(d=a)if(d=a&&b){d=b.value;var f=a?K(M(O(),a.getName())):B;d=d>=f.value}if(d){b=b||B;d=M(O(),a.getName());typeof c==="function"&&(c=c());H||(H=new aa);f=H;a=a.getName();if(f.i>0){var h=(f.u+1)%f.i;f.u=h;f.v?(f=f.o[h],f.reset(b,c,a),a=f):(f.v=h==f.i-1,a=f.o[h]=new J(b,c,a))}else a=new J(b,c,a);d.publish(a)}};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
function Q(a){return a.toString().indexOf("`")===-1}Q(a=>a``)||Q(a=>a`\0`)||Q(a=>a`\n`)||Q(a=>a`\u0000`);var ca=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;"ARTICLE SECTION NAV ASIDE H1 H2 H3 H4 H5 H6 HEADER FOOTER ADDRESS P HR PRE BLOCKQUOTE OL UL LH LI DL DT DD FIGURE FIGCAPTION MAIN DIV EM STRONG SMALL S CITE Q DFN ABBR RUBY RB RT RTC RP DATA TIME CODE VAR SAMP KBD SUB SUP I B U MARK BDI BDO SPAN BR WBR NOBR INS DEL PICTURE PARAM TRACK MAP TABLE CAPTION COLGROUP COL TBODY THEAD TFOOT TR TD TH SELECT DATALIST OPTGROUP OPTION OUTPUT PROGRESS METER FIELDSET LEGEND DETAILS SUMMARY MENU DIALOG SLOT CANVAS FONT CENTER ACRONYM BASEFONT BIG DIR HGROUP STRIKE TT".split(" ").concat(["BUTTON",
"INPUT"]);var T=class{constructor(a){this.name=a;this.target=M(O(),a).G}log(a,b){P(this.target,a!=null?a:R,b)}error(a){P(this.target,C,a)}warn(a){P(this.target,D,a)}info(a){P(this.target,E,a)}debug(a){P(this.target,R,a)}trace(a){P(this.target,S,a)}};M(O(),"");var R=new A("DEBUG",600),S=new A("TRACE",100);G.push(R);G.push(S);new T("SG/DisguisedError");
function da(a){if(a.message)return a.message;var b,c,d=((c=(b=a.retry)==null?void 0:b.delay)!=null?c:0)>0;switch(a.code){case "profile":case "401":return"To restore access to '%(url.host)s' please sign into your Chrome profile account.";case "403":return"Access to '%(url.host)s' was denied by your organization's Administrator.";case "500":case "502":case "503":case "504":return`Access to '%(url.host)s' is temporarily unavailable, ${d?"retrying shortly...":"please try again later."}`;default:return`${z[a.code]||
"Error"} while accessing '%(url.host)s', please contact your organization's Administrator.`}};function ea(a){var b=a.dataset.upgraded;if(b!==null&&typeof b==="string")return b.split(",").find(c=>c==="MaterialProgress")?a.MaterialProgress:void 0};function fa(a){function b(d){if(!d||d.length===0)return!1;var f=d.charCodeAt(0);if(!(f>=65&&f<=90||f>=97&&f<=122)&&f!==36&&f!==95)return!1;for(f=1;f<d.length;f++){let h=d.charCodeAt(f);if(!(h>=65&&h<=90||h>=97&&h<=122||h>=48&&h<=57)&&h!==36&&h!==95)return!1}return!0}var c=d=>{switch(typeof d){case "object":return d===null?"null":Array.isArray(d)?`[${d.map(c).join(", ")}]`:`{${Object.entries(d).map(([h,k])=>`${b(h)?h:`'${h}'`}: ${c(k)}`).join(", ")}}`;case "string":let f="";for(let h=0;h<d.length;h++){let k=
d[h];switch(k){case "\\":f+="\\\\";break;case "'":f+="\\'";break;case '"':f+='\\"';break;default:f+=k}}return`'${f}'`;case "function":return"function";case "undefined":return"undefined";default:return String(d)}};return c(a)};function ha(a){return x(function*(){return new Promise(b=>{setTimeout(()=>{b(void 0)},a)})}())};const ia=new URL("chrome://settings/people"),ja=new URL("https://resource");function U(a,b){a=a.classList;b.visible!==void 0&&a.toggle("invisible",!b.visible);b.display!==void 0&&a.toggle("hidden",!b.display);b.active!==void 0&&a.toggle("is-active",b.active)}const V=new T("SG/ErrorPresenter");
var ka=function(a){return x(function*(){a:{var b=a.error;switch(b.code){case "profile":case "401":b="Unauthenticated";break a;case "403":b="Access Denied";break a;default:b=z[b.code]||"Error"}}W(a,b,b);var c,d;b=(d=(c=a.error.retry)==null?void 0:c.delay)!=null?d:0;c=b>0;X(a,`Try ${c?"now":"again"}`,a.url);if(c&&a.url){U(document.getElementById("progress-wrapper"),{display:!0});let f=document.getElementById("progress");componentHandler.upgradeElement(f);let h=ea(f);if(h){c=Date.now();d=c+b*1E3;for(let k=
Date.now();k<d;k=Date.now())h.setProgress(Math.floor((k-c)/(b*10))),yield ha(b*20);h.setProgress(100);f.classList.toggle("mdl-progress__indeterminate",!0);b=document.getElementById("action");b.disabled=!0;b.textContent="Redirecting...";yield Y(a,a.url)}else V.error("Failed to upgrade progress element.")}}())},la=function(a){return x(function*(){W(a,"Internal Error","Something went wrong");X(a,"Try again",a.url)}())},ma=function(a){return x(function*(){V.trace(()=>`Presenting ${fa(a.error)}.`);switch(a.error.code){case "profile":case "401":W(a,
"Unauthenticated","Authentication Required");X(a,"Sign in",ia);break;case "403":case "500":case "502":case "503":case "504":yield ka(a);break;default:yield la(a)}var b=document.querySelectorAll("[data-i18n]");for(let c of b)b=c.getAttribute("data-i18n"),c.textContent=chrome.i18n.getMessage(b)||"PLACEHOLDER"}())},W=function(a,b,c){document.title=b;document.getElementById("heading").textContent=c;var d;b=document.getElementById("message");c=a.error;a=(d=a.url)!=null?d:ja;d=da(c);a=[{url:a}];try{var f=
sprintf(d,...a)}catch(h){f=d}b.textContent=f},X=function(a,b,c){U(document.getElementById("action-wrapper"),{display:!!c});if(c){let d=document.getElementById("action");d.textContent=b;d.onclick=()=>x(function*(){yield Y(a,c)}())}},Y=function(a,b){return x(function*(){if(a.tabId)yield chrome.tabs.update(a.tabId,{url:b.toString()});else{var c=window.location;var d=b.toString();d=ca.test(d)?d:void 0;d!==void 0&&(c.href=d)}}())},na=class{constructor(a,b,c){this.error=a;this.tabId=b;this.url=c}};const Z=new T("SG/ErrorScript");
function oa(){x(function*(){Z.debug("Initializing...");var a=new URLSearchParams(window.location.search);var b=a.get("code");if(b){var c=a.get("message");var d=Number(a.get("retry"));b={code:b};c&&(b.message=c);Number.isNaN(d)||(b.retry={delay:Math.max(0,d)});c=b}else c=void 0;c=[c||{code:"internal"},void 0,void 0];a.has("tid")&&(d=Number(a.get("tid")),Number.isInteger(d)&&(c[1]=d));a.has("url")&&(c[2]=new URL(a.get("url")));yield ma(new na(...c));Z.debug("Done.")}())}
document.addEventListener("DOMContentLoaded",()=>{Z.debug("Handling DOMContentLoaded...");oa()});/*

Copyright (c) 2007-present, Alexandru M?r??teanu <hello@alexei.ro>
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
 Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.
 Neither the name of this software nor the names of its contributors may be
  used to endorse or promote products derived from this software without
  specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
var sprintf=function(){function a(f){var h=f;if(d[h])h=d[h];else{for(var k=h,l,u=[],e=0;k;){if((l=c.text.exec(k))!==null)u.push(l[0]);else if((l=c.H.exec(k))!==null)u.push("%");else if((l=c.placeholder.exec(k))!==null){if(l[2]){e|=1;var p=[],n=l[2],g;if((g=c.key.exec(n))!==null)for(p.push(g[1]);(n=n.substring(g[0].length))!=="";)if((g=c.F.exec(n))!==null)p.push(g[1]);else if((g=c.C.exec(n))!==null)p.push(g[1]);else throw new SyntaxError("[sprintf] failed to parse named argument key");else throw new SyntaxError("[sprintf] failed to parse named argument key");
l[2]=p}else e|=2;if(e===3)throw Error("[sprintf] mixing positional and named placeholders is not (yet) supported");u.push({placeholder:l[0],A:l[1],keys:l[2],sign:l[3],j:l[4],align:l[5],width:l[6],precision:l[7],type:l[8]})}else throw new SyntaxError("[sprintf] unexpected placeholder");k=k.substring(l[0].length)}h=d[h]=u}k=arguments;l=1;u=h.length;p="";var q,I;for(n=0;n<u;n++)if(typeof h[n]==="string")p+=h[n];else if(typeof h[n]==="object"){g=h[n];if(g.keys)for(e=k[l],q=0;q<g.keys.length;q++){if(e==
void 0)throw Error(a('[sprintf] Cannot access property "%s" of undefined value "%s"',g.keys[q],g.keys[q-1]));e=e[g.keys[q]]}else e=g.A?k[g.A]:k[l++];c.K.test(g.type)&&c.J.test(g.type)&&e instanceof Function&&(e=e());if(c.N.test(g.type)&&typeof e!=="number"&&isNaN(e))throw new TypeError(a("[sprintf] expecting number but found %T",e));c.number.test(g.type)&&(I=e>=0);switch(g.type){case "b":e=parseInt(e,10).toString(2);break;case "c":e=String.fromCharCode(parseInt(e,10));break;case "d":case "i":e=parseInt(e,
10);break;case "j":e=JSON.stringify(e,null,g.width?parseInt(g.width):0);break;case "e":e=g.precision?parseFloat(e).toExponential(g.precision):parseFloat(e).toExponential();break;case "f":e=g.precision?parseFloat(e).toFixed(g.precision):parseFloat(e);break;case "g":e=g.precision?String(Number(e.toPrecision(g.precision))):parseFloat(e);break;case "o":e=(parseInt(e,10)>>>0).toString(8);break;case "s":e=String(e);e=g.precision?e.substring(0,g.precision):e;break;case "t":e=String(!!e);e=g.precision?e.substring(0,
g.precision):e;break;case "T":e=Object.prototype.toString.call(e).slice(8,-1).toLowerCase();e=g.precision?e.substring(0,g.precision):e;break;case "u":e=parseInt(e,10)>>>0;break;case "v":e=e.valueOf();e=g.precision?e.substring(0,g.precision):e;break;case "x":e=(parseInt(e,10)>>>0).toString(16);break;case "X":e=(parseInt(e,10)>>>0).toString(16).toUpperCase()}if(c.json.test(g.type))p+=e;else{if(!c.number.test(g.type)||I&&!g.sign)var y="";else y=I?"+":"-",e=e.toString().replace(c.sign,"");q=g.j?g.j===
"0"?"0":g.j.charAt(1):" ";var v=g.width-(y+e).length;v=g.width?v>0?q.repeat(v):"":"";p+=g.align?y+e+v:q==="0"?y+v+e:v+y+e}}return p}function b(f,h){return a.apply(null,[f].concat(h||[]))}var c={R:/[^s]/,O:/[^t]/,K:/[^T]/,J:/[^v]/,number:/[diefg]/,N:/[bcdiefguxX]/,json:/[j]/,P:/[^j]/,text:/^[^\x25]+/,H:/^\x25{2}/,placeholder:/^\x25(?:([1-9]\d*)\$|\(([^)]+)\))?(\+)?(0|'[^$])?(-)?(\d+)?(?:\.(\d+))?([b-gijostTuvxX])/,key:/^([a-z_][a-z_\d]*)/i,F:/^\.([a-z_][a-z_\d]*)/i,C:/^\[(\d+)\]/,sign:/^[+-]/},d=Object.create(null);
typeof exports!=="undefined"&&(exports.sprintf=a,exports.vsprintf=b);typeof window!=="undefined"&&(window.sprintf=a,window.vsprintf=b,typeof define==="function"&&define.amd&&define(function(){return{sprintf:a,vsprintf:b}}));return a}();
