// Copyright (c) 2026. Citrix Systems, Inc. All Rights Reserved. Confidential & Proprietary

/**
 * Error ID constants matching errorConfig.json
 * Use these when throwing ExtensionError with cause field
 */

export const ERROR_IDS = {
	POLICY_RETRIEVE_FAILED: 'POLICY_RETRIEVE_FAILED',
	POLICY_ENFORCE_FAILED: 'POLICY_ENFORCE_FAILED',
	EPA_NOT_INSTALLED: 'EPA_NOT_INSTALLED',
	WORKSPACE_APP_ERROR: 'WORKSPACE_APP_ERROR',
	SESSION_RECORDING_AGENT_NOT_INSTALLED: 'SESSION_RECORDING_AGENT_NOT_INSTALLED',
	SESSION_RECORDING_AGENT_VERSION_UNSUPPORTED: 'SESSION_RECORDING_AGENT_VERSION_UNSUPPORTED',
	SESSION_RECORDING_NO_RESPONSE: 'SESSION_RECORDING_NO_RESPONSE',
	SESSION_RECORDING_STOPPED: 'SESSION_RECORDING_STOPPED',
	UNKNOWN_ERROR: 'UNKNOWN_ERROR',
	FORCE_LOGOUT: 'FORCE_LOGOUT',
	FORCE_LOGOUT_WARNING: 'FORCE_LOGOUT_WARNING',
} as const;

export type ErrorId = (typeof ERROR_IDS)[keyof typeof ERROR_IDS];
